async(page)=>{
 const base='file:///C:/Users/danie/OneDrive/Desktop/parmelia-landing/parmelia-landing/recursos/laboratorio-gatopago/01-animaciones/coleccion/index.html',screens=[],runtime=[],errors=[],newIds=['creciendo','tarjeta','linterna','seguridad'];
 page.on('pageerror',e=>errors.push(e.message));await page.bringToFront();const cdp=await page.context().newCDPSession(page),window=await cdp.send('Browser.getWindowForTarget');await cdp.send('Browser.setWindowBounds',{windowId:window.windowId,bounds:{windowState:'normal'}});await cdp.detach();await page.emulateMedia({reducedMotion:'no-preference'});
 for(const width of[1280,390]){await page.setViewportSize({width,height:920});await page.goto(base);const ids=await page.locator('#animation option').evaluateAll(n=>n.map(n=>n.value));if(ids.length!==18)throw Error('Colección incompleta');
  for(const id of ids){await page.locator('#animation').selectOption(id);await page.waitForFunction(()=>!document.querySelector('#play').disabled);await page.evaluate(async()=>{await document.fonts.ready;await Promise.all([...document.images].map(i=>i.decode()));});const checks=await page.evaluate(()=>({allImages:[...document.images].every(i=>i.complete&&i.naturalWidth),recursive:[...document.fonts].some(f=>f.family==='Recursive'&&f.status==='loaded'),noOverflow:document.documentElement.scrollWidth<=innerWidth,paused:document.querySelector('#play').getAttribute('aria-pressed')==='false'}));if(Object.values(checks).some(x=>!x))throw Error(JSON.stringify({id,width,checks}));const frames=await page.locator('#frames img').count();
   if(newIds.includes(id))await page.locator('.comparison').screenshot({path:'recursos/laboratorio-gatopago/.qa/care/'+id+'-first-'+width+'.png'});
   await page.locator('#phase').fill('1000');if(!(await page.locator('#after').getAttribute('src')).endsWith('/'+String(frames).padStart(2,'0')+'.png'))throw Error('Final incorrecto '+id);if(newIds.includes(id))await page.locator('.comparison').screenshot({path:'recursos/laboratorio-gatopago/.qa/care/'+id+'-last-'+width+'.png'});
   for(const size of['96','128','768']){await page.locator('#size').selectOption(size);const box=await page.locator('#after').boundingBox();if(Math.abs(box.width-Number(size))>.1)throw Error('Tamaño incorrecto');if(size==='768'){const stage=await page.locator('.comparison article:last-child .stage').boundingBox();if(Math.abs(box.x-stage.x-2)>.1)throw Error('Padding nativo inaccesible');}if(size==='128'&&newIds.includes(id))await page.locator('.comparison').screenshot({path:'recursos/laboratorio-gatopago/.qa/care/'+id+'-128px-'+width+'.png'});}
   await page.locator('#size').selectOption('fit');await page.locator('#reset').click();await page.locator('#play').click();await page.waitForTimeout(230);const advances=Number(await page.locator('#phase').inputValue())>0;await page.locator('#play').click();const phase=await page.locator('#phase').inputValue();await page.waitForTimeout(100);if(!advances||phase!==await page.locator('#phase').inputValue())throw Error('Play/pause '+id);await page.locator('#reset').click();screens.push({id,width,frames,checks,sizes:[96,128,768],lastAccessible:true,pauseStable:true});
  }
 }
 for(const id of newIds){await page.locator('#animation').selectOption(id);await page.waitForFunction(()=>!document.querySelector('#play').disabled);await page.locator('#speed').selectOption('1');await page.evaluate(()=>{const r={steps:[],wraps:0,lastPhase:0};window.__gpCareCycle=r;r.observer=new MutationObserver(()=>{const n=Number(document.querySelector('#after').getAttribute('src').match(/\/(\d+)\.png$/)[1]);if(!r.steps.includes(n))r.steps.push(n);const phase=Number(document.querySelector('#phase').value);if(phase<r.lastPhase)r.wraps++;r.lastPhase=phase;});r.observer.observe(document.querySelector('#after'),{attributes:true,attributeFilter:['src']});});await page.locator('#play').click();const once=id!=='linterna';if(once)await page.waitForFunction(()=>document.querySelector('#phase').value==='1000'&&document.querySelector('#play').getAttribute('aria-pressed')==='false',{},{timeout:20000});else{await page.waitForFunction(()=>window.__gpCareCycle.wraps>=2,{},{timeout:20000});await page.locator('#play').click();}const r=await page.evaluate(()=>{window.__gpCareCycle.observer.disconnect();return{steps:window.__gpCareCycle.steps.sort((a,b)=>a-b),wraps:window.__gpCareCycle.wraps};}),frames=await page.locator('#frames img').count();if(r.steps.length!==frames)throw Error('Pasos omitidos '+id+' '+r.steps.length+'/'+frames);const final=await page.locator('#after').getAttribute('src');await page.waitForTimeout(240);if(once&&final!==await page.locator('#after').getAttribute('src'))throw Error('Final no conservado');runtime.push({id,frames,once,holdsFinal:once,...r});}
 await page.locator('#play').click();await page.emulateMedia({reducedMotion:'reduce'});await page.waitForFunction(()=>document.querySelector('#play').getAttribute('aria-pressed')==='false');const p=await page.locator('#phase').inputValue();await page.waitForTimeout(160);if(p!==await page.locator('#phase').inputValue())throw Error('Movimiento reducido');await page.emulateMedia({reducedMotion:'no-preference'});await page.locator('#reset').click();await page.locator('#background').click();await page.locator('#animation').selectOption('linterna');await page.waitForFunction(()=>!document.querySelector('#play').disabled);await page.locator('.comparison').screenshot({path:'recursos/laboratorio-gatopago/.qa/care/linterna-dark.png'});if(errors.length)throw Error(errors.join(';'));
 const result={checkedAt:new Date().toISOString(),screens,runtime,reducedStops:true,pageErrors:errors,scope:'18 comparativas/36 casos; cuatro nuevas reproducidas a 1x, finales o dos ciclos. No prueba de FPS móvil, NFC, rendimiento ni seguridad financiera.'};await page.evaluate(r=>window.__gpCareAudit=r,result);return result;
}
