async(page)=>{
 const base='file:///C:/Users/danie/OneDrive/Desktop/parmelia-landing/parmelia-landing/archivo/laboratorio-gatopago/01-animaciones/coleccion/index.html',screens=[],errors=[];
 page.on('pageerror',e=>errors.push(e.message));await page.bringToFront();const cdp=await page.context().newCDPSession(page),window=await cdp.send('Browser.getWindowForTarget');await cdp.send('Browser.setWindowBounds',{windowId:window.windowId,bounds:{windowState:'normal'}});await cdp.detach();await page.emulateMedia({reducedMotion:'no-preference'});
 for(const width of[1280,390]){await page.setViewportSize({width,height:920});await page.goto(base);if(await page.locator('#animation option').count()!==18)throw Error('La colección no tiene dieciocho acciones');await page.locator('#animation').selectOption('comprobante');await page.waitForFunction(()=>!document.querySelector('#play').disabled);await page.evaluate(async()=>{await document.fonts.ready;await Promise.all([...document.images].map(i=>i.decode()));});const checks=await page.evaluate(()=>({allImages:[...document.images].every(i=>i.complete&&i.naturalWidth),recursive:[...document.fonts].some(f=>f.family==='Recursive'&&f.status==='loaded'),noOverflow:document.documentElement.scrollWidth<=innerWidth,paused:document.querySelector('#play').getAttribute('aria-pressed')==='false'}));if(Object.values(checks).some(x=>!x))throw Error(JSON.stringify(checks));
  await page.locator('.comparison').screenshot({path:'archivo/laboratorio-gatopago/.qa/receipt/first-'+width+'.png'});await page.locator('#phase').fill('1000');if(!(await page.locator('#after').getAttribute('src')).endsWith('/61.png'))throw Error('Final incorrecto');await page.locator('.comparison').screenshot({path:'archivo/laboratorio-gatopago/.qa/receipt/last-'+width+'.png'});
  for(const size of['96','128','768']){await page.locator('#size').selectOption(size);const box=await page.locator('#after').boundingBox();if(Math.abs(box.width-Number(size))>.1)throw Error('Tamaño incorrecto '+size);if(size==='768'){const stage=await page.locator('.comparison article:last-child .stage').boundingBox();if(Math.abs(box.x-stage.x-2)>.1)throw Error('Padding nativo inaccesible');}if(size==='128')await page.locator('.comparison').screenshot({path:'archivo/laboratorio-gatopago/.qa/receipt/128px-'+width+'.png'});}
  await page.locator('#size').selectOption('fit');await page.locator('#reset').click();await page.locator('#play').click();await page.waitForTimeout(230);const advances=Number(await page.locator('#phase').inputValue())>0;await page.locator('#play').click();const phase=await page.locator('#phase').inputValue();await page.waitForTimeout(160);if(!advances||phase!==await page.locator('#phase').inputValue())throw Error('Play/pause');await page.locator('#reset').click();screens.push({width,checks,sizes:[96,128,768],lastAccessible:true,pauseStable:true});
 }
 await page.locator('#speed').selectOption('1');await page.evaluate(()=>{window.__gpReceiptSteps=[];window.__gpReceiptObserver=new MutationObserver(()=>{const n=Number(document.querySelector('#after').getAttribute('src').match(/\/(\d+)\.png$/)[1]);if(!window.__gpReceiptSteps.includes(n))window.__gpReceiptSteps.push(n);});window.__gpReceiptObserver.observe(document.querySelector('#after'),{attributes:true,attributeFilter:['src']});});await page.locator('#play').click();await page.waitForFunction(()=>document.querySelector('#phase').value==='1000'&&document.querySelector('#play').getAttribute('aria-pressed')==='false',{},{timeout:15000});const steps=await page.evaluate(()=>{window.__gpReceiptObserver.disconnect();return window.__gpReceiptSteps.sort((a,b)=>a-b);});if(steps.length!==61)throw Error('Pasos omitidos '+steps.length);const final=await page.locator('#after').getAttribute('src');await page.waitForTimeout(400);if(final!==await page.locator('#after').getAttribute('src'))throw Error('Final no conservado');await page.locator('#play').click();await page.emulateMedia({reducedMotion:'reduce'});await page.waitForFunction(()=>document.querySelector('#play').getAttribute('aria-pressed')==='false');const p=await page.locator('#phase').inputValue();await page.waitForTimeout(160);if(p!==await page.locator('#phase').inputValue())throw Error('No respeta reducción');await page.emulateMedia({reducedMotion:'no-preference'});await page.locator('#reset').click();if(errors.length)throw Error(errors.join(';'));
 const result={checkedAt:new Date().toISOString(),screens,steps,once:true,holdsFinal:true,reducedStops:true,pageErrors:errors,scope:'Comprobante raster a 390/1280; 61 pasos observados a 1x, tamaños y final real; no certifica FPS ni aprobación artística.'};await page.evaluate(r=>window.__gpReceiptAudit=r,result);return result;
}
