import {readFile,writeFile,mkdir} from 'node:fs/promises';
import {resolve,dirname,join} from 'node:path';
import {fileURLToPath} from 'node:url';
import {createHash} from 'node:crypto';
import sharp from 'sharp';
const lab=resolve(dirname(fileURLToPath(import.meta.url)),'..'),root=join(lab,'01-animaciones/rig-raster');
const kit=resolve(lab,'../../brandkit/03-personaje');
const original=JSON.parse(await readFile(join(lab,'01-animaciones/comparativas.json'),'utf8'));
const sha=b=>createHash('sha256').update(b).digest('hex');
await mkdir(join(root,'capas'),{recursive:true});
function bounds(raw,threshold=24){let x0=raw.info.width,y0=raw.info.height,x1=-1,y1=-1;for(let y=0;y<raw.info.height;y++)for(let x=0;x<raw.info.width;x++)if(raw.data[(y*raw.info.width+x)*4+3]>threshold){x0=Math.min(x0,x);y0=Math.min(y0,y);x1=Math.max(x1,x);y1=Math.max(y1,y);}return {x0,y0,x1,y1};}
const layers={};
async function layer(name,png,source){const data=await sharp(png).ensureAlpha().raw().toBuffer({resolveWithObject:true});const file='capas/'+name+'.png';await writeFile(join(root,file),png);const result={name,file,sha256:sha(png),width:data.info.width,height:data.info.height,bounds:bounds(data),source,dataURI:'data:image/png;base64,'+png.toString('base64')};layers[name]=result;return result;}
async function plate(source,left,right){const png=await readFile(join(lab,source)),raw=await sharp(png).ensureAlpha().raw().toBuffer({resolveWithObject:true});const {width,height}=raw.info;let separator=-1;
 for(let dx=0;dx<100&&separator<0;dx++)for(const x of [Math.floor(width/2)-dx,Math.floor(width/2)+dx]){let occupied=false;for(let y=0;y<height;y++)if(raw.data[(y*width+x)*4+3]){occupied=true;break;}if(!occupied){separator=x;break;}}
 if(separator<0)throw Error('No existe gutter completamente transparente: '+source);
 const pieces=[];for(const [name,x,w] of [[left,0,separator],[right,separator,width-separator]]){const rect={left:x,top:0,width:w,height};const b=await sharp(png).extract(rect).png().toBuffer();pieces.push(await layer(name,b,{file:source,sha256:sha(png),cell:rect,method:'separación en columna alfa cero; sin recortar silueta, recolorear ni redibujar'}));}return pieces;}
const [sitting,tail]=await plate('01-animaciones/fuentes/cola-capas-v1.png','sentado','cola');
const [headSleep,bodySleep]=await plate('01-animaciones/fuentes/siesta-capas-v2.png','cabeza-siesta','cuerpo-siesta');
const [worker,paw]=await plate('01-animaciones/fuentes/rail-capas-v2.png','cuerpo-rail','pata-rail');
const head=await layer('cabeza-neutral',await readFile(join(kit,'estaticos/expresion-neutral.png')),{file:'brandkit/03-personaje/estaticos/expresion-neutral.png',method:'copia completa sin cambios'});
const card=await layer('tarjeta-asomarse',await readFile(join(kit,'animaciones/fotogramas/asomarse/01.png')),{file:'brandkit/03-personaje/animaciones/fotogramas/asomarse/01.png',method:'copia completa sin cambios'});
const image=(id,L,x,y,scale=1)=>`<image id="${id}" href="${L.dataURI}" x="${x.toFixed(3)}" y="${y.toFixed(3)}" width="${(L.width*scale).toFixed(3)}" height="${(L.height*scale).toFixed(3)}"/>`;
const scale=.58,bodyX=384-(sitting.bounds.x0+sitting.bounds.x1)/2*scale,bodyY=82-sitting.bounds.y0*scale;
const pivot={x:bodyX+(sitting.bounds.x1-55)*scale,y:bodyY+(sitting.bounds.y1-50)*scale};
const tailX=pivot.x-(tail.bounds.x0+20)*scale,tailY=pivot.y-(tail.bounds.y1-12)*scale;
const ease=t=>t*t*(3-2*t);
async function nativeLayer(name,width,height,inner){
 const file='01-animaciones/rig-raster/capas/'+name+'-fuente.svg';
 const svg=`<svg xmlns="http://www.w3.org/2000/svg" width="${width}" height="${height}" viewBox="0 0 ${width} ${height}">${inner}</svg>`;
 await writeFile(join(lab,file),svg);
 return layer(name,await sharp(Buffer.from(svg)).png().toBuffer(),{file,sha256:sha(Buffer.from(svg)),method:'SVG original de objeto geométrico, renderizado mecánicamente; no redibuja al gato',renderedSVG:true});
}
const rail=await nativeLayer('rail-fijo',560,36,'<path fill="#0b0b0f" d="M0 0H280V36H0ZM376 0H560V36H376Z"/><path fill="#68717f" d="M4 4H280V32H4ZM376 4H556V32H376Z"/><path fill="#ffc55b" d="M36 4H48V32H36ZM108 4H120V32H108ZM180 4H192V32H180ZM252 4H264V32H252ZM420 4H432V32H420ZM492 4H504V32H492Z"/>');
const railBlock=await nativeLayer('pieza-rail',96,36,'<rect width="96" height="36" fill="#0b0b0f"/><rect x="4" y="4" width="88" height="28" fill="#ffc55b"/><path fill="#d9972c" d="M4 24H92V32H4Z"/>');
const gold=await nativeLayer('bloque-dorado',64,64,'<rect width="64" height="64" fill="#0b0b0f"/><rect x="4" y="4" width="56" height="56" fill="#ffc55b"/><path fill="#d9972c" d="M4 48H60V60H4ZM20 20H28V28H36V20H44V44H20Z"/>');
const blue=await nativeLayer('bloque-azul',64,64,'<rect width="64" height="64" fill="#0b0b0f"/><rect x="4" y="4" width="56" height="56" fill="#4169b1"/><path fill="#fff8f0" d="M16 16H48V40H32L24 48V40H16ZM22 22V34H42V22Z"/><path fill="#fff8f0" d="M26 26H30V30H26ZM34 26H38V30H34Z"/>');
const railPivot={x:424-120*Math.cos(24*Math.PI/180),y:479-18-120*Math.sin(24*Math.PI/180)};
const workerScale=.5,workerX=railPivot.x-520*workerScale,workerY=railPivot.y-560*workerScale;
const pawX=railPivot.x-(paw.bounds.x0+20)*workerScale,pawY=railPivot.y-(paw.bounds.y0+36)*workerScale;
const definitions={images:{'tail-image':'cola','body-image':'sentado','sleep-body-image':'cuerpo-siesta','sleep-head-image':'cabeza-siesta','neutral-head-image':'cabeza-neutral','stationary-card-image':'tarjeta-asomarse','worker-image':'cuerpo-rail','paw-image':'pata-rail','rail-image':'rail-fijo','rail-block-image':'pieza-rail','gold-image':'bloque-dorado','blue-image':'bloque-azul'}};
const defs=[
 {id:'cola',name:'Cola',count:61,playback:'loop',ms:i=>i===0||i===60?400:40,prompt:'../prompts/cola-capas-v1.txt',correction:'Un cuerpo raster constante y una sola cola reutilizada, que gira suavemente por su base. No hay dibujos independientes de la cabeza entre frames.',draw:t=>{const angle=9*Math.sin(t*Math.PI*2);return `<g id="tail" transform="rotate(${angle.toFixed(4)} ${pivot.x.toFixed(3)} ${pivot.y.toFixed(3)})">${image('tail-image',tail,tailX,tailY,scale)}</g><g id="body">${image('body-image',sitting,bodyX,bodyY,scale)}</g>`;}},
 {id:'siesta',name:'Siesta',count:41,playback:'loop',ms:i=>i===0||i===40?700:60,prompt:'../prompts/siesta-capas-v2.txt',correction:'La cabeza y sus orejas se mantienen fijas. La misma pieza del cuerpo respira suavemente desde el suelo; las patas pertenecen solamente al cuerpo.',draw:t=>{const sy=1+.014*(1-Math.cos(t*Math.PI*2))/2;return `<g id="body" transform="translate(0 504) scale(1 ${sy.toFixed(6)}) translate(0 -504)">${image('sleep-body-image',bodySleep,240,180,.4)}</g><g id="head">${image('sleep-head-image',headSleep,110,140,.4)}</g>`;}},
 {id:'asomarse',name:'Asomarse',count:49,playback:'once',ms:i=>i===0?600:i===48?500:50,prompt:'asomarse/reglas.json',correction:'Se reutilizan el PNG neutral original y la tarjeta original completos. Solo cambia la posición de la cabeza detrás de la tarjeta: ni ancho de tarjeta ni expresión cambian.',draw:t=>{const reveal=t<.43?ease(t/.43):t<.6?1:1-ease((t-.6)/.4);const x=48+196*reveal;return `<defs><clipPath id="occlusion"><rect x="350" y="70" width="380" height="490"/></clipPath></defs><g id="head" clip-path="url(#occlusion)">${image('neutral-head-image',head,x,128)}</g><g id="card">${image('stationary-card-image',card,160,80,2)}</g>`;}},
 {id:'reparar-rail',name:'Reparar el camino',count:61,playback:'once',ms:i=>i===0?450:i===60?800:45,prompt:'../prompts/rail-capas-v2.txt',correction:'Una cabeza/cuerpo raster fija, una pata articulada y un rail fijo. La misma pieza de 96 × 36 px desciende hasta un hueco exactamente de 96 × 36 px y conserva el final.',draw:t=>{const angle=-28+52*ease(t),r=angle*Math.PI/180,x=railPivot.x+120*Math.cos(r)-48,y=railPivot.y+120*Math.sin(r)+18;return `<g id="rail">${image('rail-image',rail,96,479)}</g><g id="piece">${image('rail-block-image',railBlock,x,y)}</g><g id="paw" transform="rotate(${angle.toFixed(4)} ${railPivot.x.toFixed(3)} ${railPivot.y.toFixed(3)})">${image('paw-image',paw,pawX,pawY,workerScale)}</g><g id="worker">${image('worker-image',worker,workerX,workerY,workerScale)}</g>`;}},
 {id:'intercambio',name:'Intercambio',count:73,playback:'once',ms:i=>i===0?500:i===72?800:40,prompt:'intercambio/reglas.json',correction:'La misma cabeza/cuerpo y una sola cola permanecen fijas. Dos bloques rasterizados desde SVG originales mantienen tamaño y color y recorren caminos separados hasta intercambiar sus posiciones. Los recorridos pasan fuera de la cara, cola y patas; desaceleran suavemente en las esquinas.',draw:t=>{const q=t;let gx,gy,bx,by;if(q<.25){const p=ease(q/.25);gx=140;gy=438-428*p;bx=668;by=438+104*p;}else if(q<.75){const p=ease((q-.25)/.5);gx=140+528*p;gy=10;bx=668-528*p;by=542;}else{const p=ease((q-.75)/.25);gx=668;gy=10+428*p;bx=140;by=542-104*p;}return `<g id="tail">${image('tail-image',tail,tailX,tailY,scale)}</g><g id="body">${image('body-image',sitting,bodyX,bodyY,scale)}</g><g id="gold">${image('gold-image',gold,gx,gy)}</g><g id="blue">${image('blue-image',blue,bx,by)}</g>`;}}
];
const records=[];
for(const d of defs){const dir=join(root,d.id);await mkdir(join(dir,'fotogramas'),{recursive:true});await mkdir(join(dir,'miniaturas'),{recursive:true});const sequence=[],rgba=[],drawings=[];
 for(let i=0;i<d.count;i++){const markup=d.draw(i/(d.count-1));const svg=`<svg xmlns="http://www.w3.org/2000/svg" width="768" height="640" viewBox="0 0 768 640" role="img" aria-label="${d.name}, rig con capas raster"><title>${d.name}: paso ${i+1}</title>${markup}</svg>`;const png=await sharp(Buffer.from(svg)).png().toBuffer();const file=d.id+'/fotogramas/'+String(i+1).padStart(2,'0')+'.png';await writeFile(join(root,file),png);sequence.push({frame:file,ms:d.ms(i),sha256:sha(png),phase:i/(d.count-1)});rgba.push(await sharp(png).ensureAlpha().raw().toBuffer());drawings.push({step:i+1,groups:[...markup.matchAll(/<g[^>]+>/g)].map(m=>m[0]),images:[...markup.matchAll(/<image id="([^"]+)"[^>]+x="([^"]+)" y="([^"]+)" width="([^"]+)" height="([^"]+)"\/>/g)].map(m=>({id:m[1],x:Number(m[2]),y:Number(m[3]),width:Number(m[4]),height:Number(m[5])}))});if(i===0)await writeFile(join(dir,'escena.svg'),svg);}
 for(const [i,s] of sequence.entries()){s.thumbnail=d.id+'/miniaturas/'+String(i+1).padStart(2,'0')+'.png';await sharp(join(root,s.frame)).resize(160,133,{fit:'fill',kernel:'nearest'}).png().toFile(join(root,s.thumbnail));}
 await sharp(Buffer.concat(rgba),{raw:{width:768,height:640*d.count,channels:4,pageHeight:640}}).webp({lossless:true,delay:sequence.map(s=>s.ms),loop:d.playback==='loop'?0:1}).toFile(join(dir,d.id+'-capas-v1.webp'));
 const selected=Array.from({length:9},(_,i)=>Math.round(i*(d.count-1)/8));const thumbnails=await Promise.all(selected.map(i=>sharp(join(root,sequence[i].frame)).resize(256,213,{fit:'fill',kernel:'nearest'}).png().toBuffer()));
 await sharp({create:{width:768,height:639,channels:4,background:{r:255,g:248,b:240,alpha:1}}}).composite(thumbnails.map((input,i)=>({input,left:(i%3)*256,top:Math.floor(i/3)*213}))).png().toFile(join(dir,'hoja-normalizada.png'));
 const ref=original.animations.find(a=>a.id===d.id).original;const source=d.id+'/escena.svg';const record={id:d.id,status:'candidato raster por capas; sin aprobación artística final',method:'image_gen para piezas de cola/siesta/rail; PNG originales intactos para asomarse; objetos geométricos propios en SVG; SVG compositor por capas y exportación mecánica con sharp',source,sourceSHA256:sha(await readFile(join(root,source))),prompt:d.prompt,canvas:{width:768,height:640},frames:d.count,totalMs:sequence.reduce((n,s)=>n+s.ms,0),playback:d.playback,preview:d.id+'/'+d.id+'-capas-v1.webp',sequence,original:{...ref,sequence:ref.sequence.map(s=>({...s,frame:'../'+s.frame}))},correction:d.correction,knownLimit:'SVG compositor con piezas PNG, no personaje vectorizado. Las extracciones de IA pueden diferir del dibujo original. Cola y pata usan giro de una pieza rígida, no flexión dibujada. Intercambio mantiene al gato atento y quieto mientras los bloques recorren la escena. Las uniones y el ritmo requieren revisión visual; ningún asset del kit se sustituye.',imageSources:definitions.images,geometry:drawings};
 await writeFile(join(dir,'manifest.json'),JSON.stringify(record,null,2));await writeFile(join(dir,'reglas.json'),JSON.stringify({method:record.method,correction:d.correction,source:record.source,bodyAnchor:{bodyX,bodyY},tailPivot:pivot,railPivot,railGap:{x:376,y:479,width:96,height:36},layerFiles:Object.values(layers).map(({dataURI,...l})=>l),frameSamplingMS:sequence.map(s=>s.ms),generator:'tools/raster-rig.mjs',originalsUnmodified:true},null,2));records.push(record);
}
await writeFile(join(root,'capas.json'),JSON.stringify({layers:Object.values(layers).map(({dataURI,...l})=>l)},null,2));
await writeFile(join(root,'comparativas.json'),JSON.stringify({status:'candidatos raster por capas, separados del kit',animations:records.map(({geometry,...r})=>r)},null,2));
await writeFile(join(root,'README.md'),[
 '# Animación con capas raster',
 'Cinco alternativas con 285 pasos PNG: cola (61), siesta (41), asomarse (49), reparar el camino (61) e intercambio (73).',
 'Las piezas de cola/siesta/rail fueron extraídas mediante image_gen integrado; se conservan fuentes y prompts, incluida la corrección de patas duplicadas y el gesto de la boca. Cada placa se separó en un gutter con alfa cero, sin retocar los píxeles. Asomarse reutiliza la cabeza y la tarjeta originales completas. Las piezas se reutilizan mediante SVG: es un compositor con PNG, no un personaje vectorizado. Los objetos geométricos nuevos tienen fuentes SVG. La oclusión de la cabeza tras la tarjeta es parte del gesto, no un recorte del PNG fuente.',
 'Cada acción incluye PNG completos, miniaturas, WebP lossless, hoja de nueve muestras, manifest compacto con tiempos/geometría y un SVG de escena editable. El código de movimiento está en `tools/raster-rig.mjs`. Las capas independientes, con hashes y celdas de origen, están en `capas.json`. El hueco del rail y su pieza miden exactamente 96 × 36 px. Intercambio usa dos recorridos separados y mantiene el gato quieto. Cola y pata son piezas rígidas articuladas, no flexión dibujada. No hay sustitución del brandkit ni integración en la app. Consultar `REVISION.md` y la evidencia de `.qa/raster-rig/`; regenerar archivos no ejecuta la prueba de navegador ni otorga aprobación artística.'
].join('\n\n')+'\n');
console.log(JSON.stringify({actions:records.length,frames:records.reduce((n,a)=>n+a.frames,0),layers:Object.keys(layers).length,root}));
