import {readFile,writeFile,mkdir} from 'node:fs/promises';
import {resolve,dirname,join} from 'node:path';
import {fileURLToPath} from 'node:url';
import {createHash} from 'node:crypto';
import sharp from 'sharp';
import {definitions,objects,sceneFor} from './care-shapes.mjs';
const lab=resolve(dirname(fileURLToPath(import.meta.url)),'..'),root=join(lab,'01-animaciones/rig-cuidados'),sha=b=>createHash('sha256').update(b).digest('hex');
await mkdir(join(root,'objetos'),{recursive:true});
const originalCatalog=JSON.parse(await readFile(join(lab,'01-animaciones/originales/catalogo.json'),'utf8'));
const base=JSON.parse(await readFile(join(lab,'01-animaciones/rig-gestos/reposo/manifest.json'),'utf8')),rules=JSON.parse(await readFile(join(lab,'01-animaciones/rig-gestos/reposo/reglas.json'),'utf8')),layerCatalog=JSON.parse(await readFile(join(lab,'01-animaciones/rig-gestos/capas.json'),'utf8')).layers;
const sources=[],tags={};
for(const placement of base.geometry[0].images){const layer=layerCatalog.find(a=>a.name===base.imageSources[placement.id]),file='01-animaciones/rig-gestos/'+layer.file,png=await readFile(join(lab,file));sources.push({file,sha256:sha(png),placement,id:placement.id});tags[placement.id]=`<image id="${placement.id}" href="data:image/png;base64,${png.toString('base64')}" x="${placement.x.toFixed(3)}" y="${placement.y.toFixed(3)}" width="${placement.width.toFixed(3)}" height="${placement.height.toFixed(3)}"/>`;}
const R={shoulder:rules.shoulder,ground:rules.ground,tailImage:`<g id="tail" transform="translate(768 0) scale(-1 1)">${tags['tail-image']}</g>`,bodyImage:`<g id="body">${tags['body-image']}</g>`,headImage:`<g id="head">${tags['head-image']}</g>`,armImage:tags['arm-image']};
const nativeSources=[];
for(const [id,o] of Object.entries(objects)){const [x,y,w,h]=o.box,svg=`<svg xmlns="http://www.w3.org/2000/svg" width="${w}" height="${h}" viewBox="${x} ${y} ${w} ${h}" role="img"><title>${o.name}</title>${o.body}</svg>`,file='objetos/'+id+'.svg';await writeFile(join(root,file),svg);nativeSources.push({file,sha256:sha(Buffer.from(svg))});}
const records=[];
for(const d of definitions){const dir=join(root,d.id);await mkdir(join(dir,'fotogramas'),{recursive:true});await mkdir(join(dir,'miniaturas'),{recursive:true});const sequence=[],rgba=[],geometry=[];
 for(let i=0;i<d.frames;i++){const t=i/(d.frames-1),S=sceneFor(d.id,t,R),svg=`<svg xmlns="http://www.w3.org/2000/svg" width="768" height="640" viewBox="0 0 768 640"><title>${d.name}, paso ${i+1}</title>${S.markup}</svg>`,png=await sharp(Buffer.from(svg)).png().toBuffer(),num=String(i+1).padStart(2,'0'),frame=d.id+'/fotogramas/'+num+'.png',thumbnail=d.id+'/miniaturas/'+num+'.png';await writeFile(join(root,frame),png);await sharp(png).resize(160,133,{kernel:'nearest',fit:'fill'}).png().toFile(join(root,thumbnail));sequence.push({frame,thumbnail,phase:t,ms:i===0?d.firstMs:i===d.frames-1?d.lastMs:d.stepMs,sha256:sha(png)});rgba.push(await sharp(png).ensureAlpha().raw().toBuffer());geometry.push({step:i+1,state:S.state});if(i===0)await writeFile(join(dir,'escena.svg'),svg);}
 const preview=d.id+'/'+d.id+'-capas-v1.webp';await sharp(Buffer.concat(rgba),{raw:{width:768,height:640*d.frames,channels:4,pageHeight:640}}).webp({lossless:true,loop:d.playback==='loop'?0:1,delay:sequence.map(s=>s.ms)}).toFile(join(root,preview));
 const samples=Array.from({length:9},(_,i)=>Math.round(i*(d.frames-1)/8)),tiles=await Promise.all(samples.map(i=>sharp(join(root,sequence[i].frame)).resize(256,213,{fit:'fill',kernel:'nearest'}).png().toBuffer()));await sharp({create:{width:768,height:639,channels:4,background:'#fff8f0'}}).composite(tiles.map((input,i)=>({input,left:i%3*256,top:Math.floor(i/3)*213}))).png().toFile(join(dir,'hoja-normalizada.png'));
 const original=originalCatalog.animations.find(a=>a.id===d.id);if(!original)throw Error('Falta referencia original '+d.id);
 const record={id:d.id,name:d.name,status:'candidato raster independiente; sin aprobación artística final',method:'cuatro piezas PNG reutilizadas, objetos SVG nativos y montaje determinista',canvas:{width:768,height:640},frames:d.frames,totalMs:sequence.reduce((n,s)=>n+s.ms,0),playback:d.playback,preview,source:d.id+'/escena.svg',sourceSHA256:sha(await readFile(join(dir,'escena.svg'))),prompt:d.id+'/reglas.json',sequence,original,correction:d.correction,knownLimit:'Pata articulada rígidamente y gato frontal sentado; no se recrea el perfil del original ni se dibujan nuevas flexiones. Cola reflejada al otro lado como transformación de montaje, sin retoque de sus píxeles. Objetos geométricos SVG propios, no objetos raster originales. Las señales y el brote son ejemplos, no prueba de disponibilidad, lectura NFC, rentabilidad, autorización ni seguridad. No se sustituyen originales ni se integra en la app.',sources,nativeSources,rules:R,geometry};
 await writeFile(join(dir,'manifest.json'),JSON.stringify(record,null,2));await writeFile(join(dir,'reglas.json'),JSON.stringify({generator:'tools/care-actions.mjs',geometry:'tools/care-shapes.mjs',correction:d.correction,frames:d.frames,ground:520,shoulder:rules.shoulder,objectGripDistance:d.id==='seguridad'?110:96,bodyHeadTailStationary:true,tailMirror:'translate(768 0) scale(-1 1)',objectsNative:true,originalsUnmodified:true},null,2));records.push(record);
}
await writeFile(join(root,'comparativas.json'),JSON.stringify({status:'cuatro acciones propuestas; fuentes reutilizadas sin nueva generación de imagen',animations:records.map(({geometry,rules,...a})=>a)},null,2));
console.log(JSON.stringify({actions:records.length,frames:records.reduce((n,a)=>n+a.frames,0),rasterSources:sources.length,nativeObjects:nativeSources.length,details:records.map(a=>({id:a.id,frames:a.frames,totalMs:a.totalMs}))}));
