import {readFile,writeFile,mkdir} from 'node:fs/promises';
import {dirname,resolve,join} from 'node:path';
import {fileURLToPath} from 'node:url';
import {createHash} from 'node:crypto';
const lab=resolve(dirname(fileURLToPath(import.meta.url)),'..');
const mode=process.argv[2]||'principal';
const raster=['raster','acciones','gestos','documento','cuidados','coleccion'].includes(mode);
const rig=process.argv[2]==='rig'||(raster&&mode!=='principal');
const directory='01-animaciones'+(mode==='principal'?'':mode==='coleccion'?'/coleccion':mode==='cuidados'?'/rig-cuidados':mode==='documento'?'/rig-documento':mode==='gestos'?'/rig-gestos':mode==='acciones'?'/rig-acciones':raster?'/rig-raster':rig?'/rig-controlado':'');
await mkdir(join(lab,directory),{recursive:true});
let data;
if(mode==='principal'){
 data=JSON.parse(await readFile(join(lab,'01-animaciones/comparativas.json'),'utf8'));
 await writeFile(join(lab,directory,'comparativas-vigentes.json'),JSON.stringify({...data,status:'Restauradas las cinco propuestas previas al montaje por capas; no son nuevas ilustraciones ni aprobación artística.'},null,2));
}else if(mode==='coleccion'){
 const animations=[];
 const previous=JSON.parse(await readFile(join(lab,'01-animaciones/comparativas.json'),'utf8')).animations;
 for(const dir of ['rig-raster','rig-acciones','rig-gestos','rig-documento','rig-cuidados']){
  const source=JSON.parse(await readFile(join(lab,'01-animaciones',dir,'comparativas.json'),'utf8'));
  for(const old of source.animations){const replacement=dir==='rig-raster'?previous.find(r=>r.id===old.id):null,a=replacement||old,prefix=replacement?'../':'../'+dir+'/';
   const original=replacement?{...a.original,sequence:a.original.sequence.map(s=>({...s,frame:'../'+s.frame}))}:a.original;
   const sequence=[];
   for(const s of a.sequence){const sha256=s.sha256||createHash('sha256').update(await readFile(join(lab,'01-animaciones',s.frame))).digest('hex');sequence.push({...s,sha256,frame:prefix+s.frame,thumbnail:s.thumbnail?prefix+s.thumbnail:undefined});}
   animations.push({...a,original,status:replacement?'Propuesta previa restaurada; las iteraciones por capas se retiraron por rechazo visual.':a.status,source:prefix+a.source,preview:prefix+a.preview,prompt:prefix+a.prompt,sheet:prefix+a.id+'/hoja-normalizada.png',manifest:prefix+a.id+'/manifest.json',sequence});
  }
 }
 data={status:animations.length+' candidatos raster, agrupados sin copiar o modificar sus fuentes',animations};
 // El catálogo inicial es fuente histórica de los originales; nunca lo sobrescribir.
 await writeFile(join(lab,directory,mode==='principal'?'comparativas-vigentes.json':'comparativas.json'),JSON.stringify(data,null,2));
}else data=JSON.parse(await readFile(join(lab,directory,'comparativas.json'),'utf8'));
const names={cola:'Cola',siesta:'Siesta',asomarse:'Asomarse','reparar-rail':'Reparar el camino',intercambio:'Intercambio',caminata:'Caminata','preparando-pago':'Preparando el pago',mantenimiento:'Mantenimiento',reposo:'Reposo',saludo:'Saludo',salto:'Salto breve','meti-la-pata':'Error recuperable',oreja:'Oreja',comprobante:'Comprobante ilustrado',creciendo:'Cuidar un brote',tarjeta:'Acercar la tarjeta',linterna:'Buscar con luz',seguridad:'Resguardar la llave'};
const html=`<!doctype html><html lang="es"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Fotogramas · GatoPago Laboratorio</title><link rel="stylesheet" href="../assets/laboratorio.css"><link rel="icon" href="../assets/simbolo.svg"><style>
.comparison{display:grid;grid-template-columns:1fr 1fr;gap:24px}.comparison article{min-width:0}.stage{height:360px;display:flex;align-items:center;justify-content:center;overflow:auto;border:2px solid var(--ink);background-color:#fffdf9;background-image:linear-gradient(45deg,#eee4d8 25%,transparent 25%),linear-gradient(-45deg,#eee4d8 25%,transparent 25%),linear-gradient(45deg,transparent 75%,#eee4d8 75%),linear-gradient(-45deg,transparent 75%,#eee4d8 75%);background-size:24px 24px;background-position:0 0,0 12px,12px -12px,-12px 0}.stage img{max-width:96%;max-height:96%;object-fit:contain;image-rendering:pixelated}.dark .stage{background:#15151b}.frames{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:12px}.frames figure{margin:0;border:1px solid var(--edge);padding:8px;background:var(--paper)}.frames img{width:100%;height:160px;object-fit:contain;image-rendering:pixelated;background:#eee4d8}.frames figcaption{font-size:12px}.downloads{display:flex;flex-wrap:wrap;gap:12px}.verdict{font-size:13px;border:1px solid var(--edge);padding:12px 16px;background:var(--paper)}input[type=range]{width:220px;max-width:100%;min-height:44px}button:disabled{opacity:.5;cursor:wait}.steps{font-variation-settings:'MONO' 1;font-size:12px}.zoomed img{max-width:none;max-height:none;width:640px;height:auto;flex-shrink:0}.zoomed{justify-content:flex-start;align-items:flex-start}@media(max-width:600px){.comparison{grid-template-columns:1fr}.stage{height:300px}.frames{grid-template-columns:repeat(2,minmax(0,1fr))}.controls label{width:100%;justify-content:space-between}}
</style></head><body><div class="wrap"><header class="mast"><a class="brand" href="../index.html"><img src="../assets/simbolo.svg" alt="">GatoPago <span class="pill">LAB</span></a><span class="eyebrow">01 / Antes y después</span></header><section class="hero"><span class="eyebrow">Fotogramas, no promesas</span><h1>Un personaje.<br>La misma identidad.</h1><p>Cinco acciones en revisión. El original queda intacto y cada propuesta declara qué corrige y dónde todavía falla. Las fuentes generadas y sus prompts también se pueden descargar.</p></section>
<div class="controls"><label>Acción <select id="animation">${data.animations.map(a=>`<option value="${a.id}">${names[a.id]}</option>`).join('')}</select></label><button id="play" aria-pressed="false" disabled>Preparando imágenes</button><button id="reset">Inicio</button><label>Fase <input id="phase" type="range" min="0" max="1000" value="0"></label><label>Velocidad <select id="speed"><option value=".5">0,5×</option><option value="1" selected>1×</option><option value="2">2×</option></select></label><button id="background" aria-pressed="false">Fondo oscuro</button><button id="zoom" aria-pressed="false">Tamaño de detalle</button></div>
<p id="info" class="steps" role="status"></p><div class="comparison"><article><span class="eyebrow">Referencia conservada</span><h2>Original</h2><div class="stage"><img id="before" alt="Fotograma original"></div><p id="before-meta" class="notes"></p><a id="original-download" class="download" download>WebP original</a></article><article><span class="eyebrow">Candidato independiente</span><h2 id="after-title">Propuesta</h2><div class="stage"><img id="after" alt="Fotograma propuesto"></div><p id="after-meta" class="notes"></p><a id="proposed-download" class="download" download>WebP propuesto</a></article></div>
<p class="notes"><a href="rig-controlado/index.html">Comparar también las pruebas SVG por capas ↗</a></p><p class="notes">La fase sincroniza las acciones, no los milisegundos. Los tiempos originales se conservan. El ajuste de tamaño muestra el lienzo completo; «Tamaño de detalle» permite desplazarse por él sin ocultar partes de la imagen.</p><aside class="spec"><h2>Corrección y límites</h2><p id="correction"></p><p id="limit"></p></aside><p id="verdict" class="verdict"></p><h2>Fotogramas de la propuesta</h2><div id="frames" class="frames"></div><div class="downloads"><a id="sheet-download" class="download" download>Hoja normalizada</a><a id="manifest-download" class="download" download>Manifest y tiempos</a><a id="source-download" class="download" download>Fuente generada</a><a id="prompt-download" class="download" download>Prompt exacto</a></div><footer class="notes">Pausado al entrar. Las acciones de una sola ejecución conservan su final. Cambiar a movimiento reducido o salir de la pestaña detiene la reproducción. Ninguna ilustración confirma una operación financiera.</footer></div><script>
const catalog=${JSON.stringify(data.animations)},names=${JSON.stringify(names)};
const $=s=>document.querySelector(s),media=matchMedia('(prefers-reduced-motion: reduce)');
let current=catalog[0],playing=false,phase=0,last=0,handle=0,revision=0,ready=false;
const cache=new Map();
function load(file){if(!cache.has(file))cache.set(file,new Promise((resolve,reject)=>{const img=new Image();img.onload=()=>resolve(img);img.onerror=()=>reject(Error('No se cargó '+file));img.src=file}));return cache.get(file)}
function frameAt(sequence,total,p){let time=Math.min(1,Math.max(0,p))*total,end=0;for(let i=0;i<sequence.length;i++){end+=sequence[i].ms;if(time<end||i===sequence.length-1)return{...sequence[i],number:i+1}}}
function paint(){const b=frameAt(current.original.sequence,current.original.totalMs,phase),a=frameAt(current.sequence,current.totalMs,phase);$('#before').setAttribute('src',b.frame);$('#after').setAttribute('src',a.frame);$('#before').alt=names[current.id]+', original, paso '+b.number;$('#after').alt=names[current.id]+', propuesta, paso '+a.number;$('#info').textContent=names[current.id]+' · original '+b.number+'/'+current.original.sequence.length+' · propuesta '+a.number+'/'+current.sequence.length+(phase===1?' · final conservado':'');$('#phase').value=Math.round(phase*1000)}
function setPlay(on){playing=on&&ready;cancelAnimationFrame(handle);last=0;$('#play').setAttribute('aria-pressed',String(playing));$('#play').textContent=playing?'Pausar':'Reproducir';if(playing)handle=requestAnimationFrame(tick)}
function tick(now){if(!playing)return;if(last){phase+=(now-last)*Number($('#speed').value)/current.totalMs;if(phase>=1){if(current.playback==='loop')phase%=1;else{phase=1;paint();setPlay(false);return}}}last=now;paint();handle=requestAnimationFrame(tick)}
async function select(){const token=++revision;setPlay(false);phase=0;current=catalog.find(a=>a.id===$('#animation').value);ready=false;$('#play').disabled=true;$('#play').textContent='Preparando imágenes';$('#after-title').textContent='Propuesta · '+names[current.id];$('#before-meta').textContent=current.original.frames+' poses · '+current.original.sequence.length+' pasos · '+current.original.totalMs+' ms';$('#after-meta').textContent=current.frames+' pasos · '+current.totalMs+' ms · '+(current.playback==='loop'?'loop':'una vez');$('#correction').textContent=current.correction;$('#limit').textContent=current.knownLimit;$('#verdict').textContent=current.status;$('#original-download').href='original/'+current.id+'.webp';$('#proposed-download').href=current.preview;$('#sheet-download').href=current.id+'/hoja-normalizada.png';$('#manifest-download').href=current.id+'/manifest.json';$('#source-download').href=current.source;$('#prompt-download').href=current.prompt;$('#frames').innerHTML=current.sequence.map((s,i)=>'<figure><a href="'+s.frame+'" download><img src="'+s.frame+'" alt="'+names[current.id]+', propuesta '+(i+1)+'" loading="eager"></a><figcaption>'+(i+1)+' · '+s.ms+' ms'+(s.sourcePose?' · pose '+s.sourcePose:'')+(s.svg?' · <a href="'+s.svg+'" download>SVG editable</a>':'')+'</figcaption></figure>').join('');paint();try{await Promise.all([...new Set([...current.sequence,...current.original.sequence].map(s=>s.frame))].map(load));if(token!==revision)return;ready=true;$('#play').disabled=false;$('#play').textContent='Reproducir'}catch(error){if(token===revision)$('#info').textContent=error.message}}
$('#animation').addEventListener('change',select);$('#play').addEventListener('click',()=>{if(!playing&&phase===1)phase=0;setPlay(!playing)});$('#reset').addEventListener('click',()=>{setPlay(false);phase=0;paint()});$('#phase').addEventListener('input',e=>{setPlay(false);phase=Number(e.target.value)/1000;paint()});$('#background').addEventListener('click',e=>{const dark=document.body.classList.toggle('dark');e.target.setAttribute('aria-pressed',String(dark));e.target.textContent=dark?'Fondo claro':'Fondo oscuro'});$('#zoom').addEventListener('click',e=>{const zoom=e.target.getAttribute('aria-pressed')!=='true';document.querySelectorAll('.stage').forEach(s=>s.classList.toggle('zoomed',zoom));e.target.setAttribute('aria-pressed',String(zoom));e.target.textContent=zoom?'Ajustar al escenario':'Tamaño de detalle'});media.addEventListener('change',e=>{if(e.matches)setPlay(false)});document.addEventListener('visibilitychange',()=>{if(document.hidden)setPlay(false)});select();
</script></body></html>`;
let output=rig?html.replace('href="rig-controlado/index.html"','href="../index.html"').replace('Comparar también las pruebas SVG por capas','Volver a los candidatos raster').replaceAll('../assets/','../../assets/').replace('href="../index.html"','href="../index.html"').replace('Las fuentes generadas y sus prompts también se pueden descargar.','Estas alternativas son SVG por capas: misma cabeza y movimiento determinista, con un cuerpo vectorial nuevo aún sin aprobación.').replace('WebP original</a>','WebP original</a>').replace("'original/'+current.id+'.webp'","'../original/'+current.id+'.webp'").replace('Fuente generada</a>','Primer SVG editable</a>').replace('Prompt exacto</a>','Reglas de escena</a>'):html;
if(raster)output=output.replace('Cinco acciones en revisión.',data.animations.length+' acciones raster por capas en revisión.').replace('Estas alternativas son SVG por capas: misma cabeza y movimiento determinista, con un cuerpo vectorial nuevo aún sin aprobación.','Estas alternativas reutilizan piezas PNG estables; el SVG solo compone la escena. No son ilustraciones vectorizadas ni arte final aprobado.').replace('Reglas de escena</a>','Prompt o reglas de montaje</a>').replace('const token=++revision;setPlay(false);','const token=++revision;setPlay(false);cache.clear();').replace('src="\'+s.frame+\'" alt="','src="\'+(s.thumbnail||s.frame)+\'" alt="');
if(rig)output=output.replace('<a class="brand" href="../index.html">','<a class="brand" href="../../index.html">');
if(raster){
 output=output.replace('El ajuste de tamaño muestra el lienzo completo;','Los tamaños del selector son el ancho del lienzo, no la altura del gato. El ajuste de tamaño muestra el lienzo completo;');
 output=output.replace("current.id+'/hoja-normalizada.png'","current.sheet||current.id+'/hoja-normalizada.png'").replace("current.id+'/manifest.json'","current.manifest||current.id+'/manifest.json'");
 output=output.replace('<button id="zoom"', '<label>Tamaño <select id="size"><option value="fit">Ajustar</option><option value="96">96 px</option><option value="128">128 px</option><option value="256">256 px</option><option value="768">768 px</option></select></label><button id="zoom"');
 output=output.replace('</style>','.stage.native-size{justify-content:flex-start;align-items:flex-start}</style>');
 output=output.replace('media.addEventListener(\'change\'',"$('#size').addEventListener('change',e=>{document.querySelectorAll('.stage').forEach(stage=>{stage.classList.remove('zoomed');stage.classList.toggle('native-size',e.target.value==='768');});$('#zoom').setAttribute('aria-pressed','false');$('#zoom').textContent='Tamaño de detalle';document.querySelectorAll('.stage img').forEach(img=>{img.style.width=e.target.value==='fit'?'':e.target.value+'px';img.style.maxWidth=e.target.value==='768'?'none':'';img.style.maxHeight=e.target.value==='768'?'none':''});});$('#zoom').addEventListener('click',()=>{document.querySelectorAll('.stage').forEach(s=>s.classList.remove('native-size'));document.querySelectorAll('.stage img').forEach(img=>{img.style.width='';img.style.maxWidth='';img.style.maxHeight='';});$('#size').value='fit';});media.addEventListener('change'");
 output=output.replace('<p class="notes"><a href="../index.html">','<p class="notes"><a href="../coleccion/index.html">Ver todas las acciones raster juntas ↗</a> · <a href="../originales/index.html">Veinte originales ↗</a></p><p class="notes"><a href="../index.html">');
}
if(mode==='principal')output=output.replace('<p class="notes"><a href="rig-controlado/index.html">Comparar también las pruebas SVG por capas ↗</a></p>','<p class="notes">Restauradas las cinco propuestas anteriores, sin cambiar sus PNG ni sus WebP. Los montajes por capas fueron retirados por rechazo visual. <a href="originales/index.html">Veinte originales conservados ↗</a> · <a href="coleccion/index.html">Colección completa ↗</a></p>');
if(mode==='coleccion')output=output.replace('Estas alternativas reutilizan piezas PNG estables; el SVG solo compone la escena. No son ilustraciones vectorizadas ni arte final aprobado.','Cola, siesta, asomarse, camino e intercambio recuperan sus versiones anteriores. Las demás acciones no cambian. Cada secuencia declara su método y sus límites; no hay arte final aprobado.');
if(mode==='raster')output=output.replace('<section class="hero">','<aside class="spec"><h2>Iteración retirada</h2><p>Estas cinco propuestas fueron rechazadas por sus cambios de apariencia. Se conservan solo como historial; <a href="../index.html">abrir las versiones restauradas</a>.</p></aside><section class="hero">');
await writeFile(join(lab,directory,'index.html'),output);
console.log(JSON.stringify({comparisons:data.animations.length,frames:data.animations.reduce((n,a)=>n+a.sequence.length,0),html:directory+'/index.html'}));
