import sharp from 'sharp';
import {readdir} from 'node:fs/promises';
import {resolve,dirname,join} from 'node:path';
import {fileURLToPath} from 'node:url';
const lab=resolve(dirname(fileURLToPath(import.meta.url)),'..');
const dir=join(lab,'.qa/manual');
const files=(await readdir(dir)).filter(x=>/^page-\d+\.png$/.test(x)).sort((a,b)=>Number(a.match(/\d+/)[0])-Number(b.match(/\d+/)[0]));
const cells=await Promise.all(files.map(async(file,i)=>({input:await sharp(join(dir,file)).resize(300,425,{fit:'contain',background:'#eee4d8'}).png().toBuffer(),left:(i%4)*312+6,top:Math.floor(i/4)*437+6})));
await sharp({create:{width:1248,height:Math.ceil(files.length/4)*437,channels:3,background:'#eee4d8'}}).composite(cells).png().toFile(join(dir,'contact.png'));
console.log({pages:files.length});
