const ink='#0b0b0f', fire='#f85239', oat='#eee4d8';
export const motions = [
 {id:'ruta',title:'El camino',use:'Preparación indeterminada: no representa porcentaje ni liquidación.',duration:2400,body:`<path d="M24 80H280" stroke="${oat}" stroke-width="4"/><path d="M24 80H280" stroke="${ink}" stroke-width="2" stroke-dasharray="8 8"/><g class="packet"><rect x="16" y="72" width="16" height="16" fill="${fire}"/><rect x="20" y="76" width="8" height="8" fill="${ink}"/></g>`,css:'.packet{animation:travel 2.4s cubic-bezier(.45,0,.25,1) infinite}@keyframes travel{0%{transform:translateX(0);opacity:0}5%,10%{transform:translateX(0);opacity:1}80%,92%{transform:translateX(256px);opacity:1}97%{transform:translateX(256px);opacity:0}100%{transform:translateX(0);opacity:0}}',staticCSS:'.packet{transform:translateX(128px);opacity:1}'},
 {id:'conexion',title:'Puntos conectados',use:'Exploración de ruta; el destino solo se confirma con datos reales.',duration:2800,body:`<path d="M48 104V48H248V104" fill="none" stroke="${oat}" stroke-width="4"/><path class="trace" d="M48 104V48H248V104" fill="none" stroke="${fire}" stroke-width="4"/><rect x="40" y="96" width="16" height="16" fill="${ink}"/><rect x="240" y="96" width="16" height="16" fill="${ink}"/>`,css:'.trace{stroke-dasharray:312;animation:draw 2.8s ease-in-out infinite}@keyframes draw{0%{stroke-dashoffset:312;opacity:0}5%,10%{stroke-dashoffset:312;opacity:1}75%,90%{stroke-dashoffset:0;opacity:1}97%{stroke-dashoffset:0;opacity:0}100%{stroke-dashoffset:312;opacity:0}}',staticCSS:'.trace{stroke-dasharray:none;opacity:1}'},
 {id:'confirmacion',title:'Una confirmación',use:'Una vez después de recibir confirmación del sistema, no antes.',duration:650,once:true,body:`<rect x="120" y="48" width="64" height="64" fill="none" stroke="${ink}" stroke-width="2"/><path class="check" d="m134 80 12 12 24-28" fill="none" stroke="${fire}" stroke-width="6"/>`,css:'.check{stroke-dasharray:54;animation:check .65s cubic-bezier(.2,.7,.2,1) both}@keyframes check{from{stroke-dashoffset:54}to{stroke-dashoffset:0}}',staticCSS:'.check{stroke-dashoffset:0}'},
 {id:'intercambio',title:'Dos trayectos',use:'Ejemplo visual de cambiar; no indica una tasa ni ejecución.',duration:2600,body:`<path d="M64 60H240M64 100H240" stroke="${oat}" stroke-width="2"/><g class="out"><rect x="56" y="52" width="16" height="16" fill="${fire}"/></g><g class="back"><rect x="232" y="92" width="16" height="16" fill="${ink}"/></g><path d="m232 52 8 8-8 8M72 92l-8 8 8 8" stroke="${ink}" stroke-width="2" fill="none"/>`,css:'.out,.back{animation:exchange 2.6s cubic-bezier(.4,0,.2,1) infinite}.back{animation-name:return}@keyframes exchange{0%{transform:translateX(0);opacity:0}5%,15%{transform:translateX(0);opacity:1}80%,92%{transform:translateX(176px);opacity:1}97%{transform:translateX(176px);opacity:0}100%{transform:translateX(0);opacity:0}}@keyframes return{0%{transform:translateX(0);opacity:0}5%,15%{transform:translateX(0);opacity:1}80%,92%{transform:translateX(-176px);opacity:1}97%{transform:translateX(-176px);opacity:0}100%{transform:translateX(0);opacity:0}}',staticCSS:'.out{transform:translateX(88px);opacity:1}.back{transform:translateX(-88px);opacity:1}'},
 {id:'espera',title:'Pulso discreto',use:'Espera sin tiempo estimado: un pulso de opacidad, sin parpadeos rápidos.',duration:1800,body:`<rect x="144" y="72" width="16" height="16" fill="${fire}" class="pulse"/><rect x="112" y="76" width="8" height="8" fill="${oat}"/><rect x="184" y="76" width="8" height="8" fill="${oat}"/>`,css:'.pulse{animation:pulse 1.8s ease-in-out infinite}@keyframes pulse{0%,100%{opacity:1}50%{opacity:.35}}',staticCSS:'.pulse{opacity:1}'},
 {id:'entrada',title:'Aparecer sin ruido',use:'Entrada de tarjeta, una vez. Sin rebotes ni desplazamientos de layout.',duration:280,once:true,body:`<g class="card"><rect x="64" y="40" width="180" height="88" fill="${oat}"/><rect x="60" y="36" width="180" height="88" fill="#fffdf9" stroke="${ink}" stroke-width="2"/><rect x="76" y="52" width="24" height="24" fill="${fire}"/><path d="M116 58h100M116 70h64M76 98h140" stroke="${ink}" stroke-width="2"/></g>`,css:'.card{animation:enter .28s cubic-bezier(.2,.7,.2,1) both}@keyframes enter{from{transform:translateY(8px);opacity:0}to{transform:translateY(0);opacity:1}}',staticCSS:'.card{transform:none;opacity:1}'}
];
export function motionSVG(motion,reduced=false) {
 return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 304 160" role="img" aria-labelledby="motion-title-${motion.id} motion-desc-${motion.id}"><title id="motion-title-${motion.id}">${motion.title}</title><desc id="motion-desc-${motion.id}">${motion.use}</desc><style>${reduced?motion.staticCSS:motion.css+'@media(prefers-reduced-motion:reduce){*{animation:none!important}'+motion.staticCSS+'}'}</style>${motion.body}</svg>`;
}
