import {readFile,writeFile,mkdir,copyFile} from 'node:fs/promises';
import {resolve,dirname,join} from 'node:path';
import {fileURLToPath} from 'node:url';
import {createHash} from 'node:crypto';
const lab=resolve(dirname(fileURLToPath(import.meta.url)),'..'),kit=resolve(lab,'../../brandkit/03-personaje/animaciones');
const root=join(lab,'01-animaciones/originales');
const source=await readFile(join(kit,'manifest.json'));
const catalog=JSON.parse(source).animations;
const hash=b=>createHash('sha256').update(b).digest('hex');
await mkdir(root,{recursive:true});
const animations=[];
for(const a of catalog){
 await mkdir(join(lab,'01-animaciones/original',a.id),{recursive:true});
 const frames=new Map(),sequence=[];
 for(const s of a.sequence){
  const target='../original/'+a.id+'/'+s.frame.split('/').at(-1);
  if(!frames.has(s.frame)){
   const b=await readFile(join(kit,s.frame));
   await copyFile(join(kit,s.frame),join(root,target));frames.set(s.frame,hash(b));
  }
  sequence.push({frame:target,ms:s.ms,sha256:frames.get(s.frame)});
 }
 await copyFile(join(kit,a.preview),join(lab,'01-animaciones/original',a.id+'.webp'));
 animations.push({...a,preview:'../original/'+a.id+'.webp',sequence});
}
await writeFile(join(root,'catalogo.json'),JSON.stringify({source:'brandkit/03-personaje/animaciones/manifest.json',sourceSHA256:hash(source),scope:'copias sin modificaciones para revisar reproducción y tiempos; no son correcciones',animations},null,2));
const html=`<!doctype html><html lang="es"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Revisión de originales · GatoPago</title><link rel="stylesheet" href="../../assets/laboratorio.css"><link rel="icon" href="../../assets/simbolo.svg"><style>
.stage{height:360px;border:2px solid var(--ink);display:flex;align-items:center;justify-content:center;margin:28px 0;background:var(--paper)}.stage img{width:var(--size,128px);height:auto;image-rendering:pixelated;max-width:90%;max-height:90%;object-fit:contain}.timeline{display:grid;grid-template-columns:repeat(auto-fit,minmax(108px,1fr));gap:12px;margin:24px 0}.timeline button{display:block;padding:8px;font-size:11px;font-weight:400}.timeline img{display:block;width:80px;height:80px;object-fit:contain;image-rendering:pixelated;margin:auto auto 6px}.timeline button[aria-current=true]{outline:3px solid var(--fire);outline-offset:2px}.controls input[type=range]{width:min(220px,60vw)}.controls label{max-width:100%}.steps{font-size:13px;font-variation-settings:'MONO' 1}.stage.dark{background:#15151b}@media(max-width:600px){.stage{height:280px}.controls label{flex-wrap:wrap}}
</style></head><body><div class="wrap"><header class="mast"><a class="brand" href="../index.html"><img src="../../assets/simbolo.svg" alt="">GatoPago <span class="pill">LAB</span></a><span class="eyebrow">20 originales / revisión</span></header><section class="hero"><span class="eyebrow">Sin modificar el arte</span><h1>Mirar el movimiento,<br>no solo las poses.</h1><p>Las veinte secuencias originales, con sus tiempos reales. La revisión permite comprobar registro, cierre y cambios de anatomía a tamaño de app. No implica aprobación visual.</p></section><div class="controls"><label>Acción <select id="action">${animations.map(a=>`<option value="${a.id}">${a.name}</option>`).join('')}</select></label><button id="play" aria-pressed="false" disabled>Preparando</button><button id="reset">Inicio</button><button id="prev" aria-label="Fotograma anterior">←</button><button id="next" aria-label="Fotograma siguiente">→</button><label>Fotograma <input id="frame" type="range" min="0" max="1" value="0"></label><label>Velocidad <select id="speed"><option value=".5">0,5×</option><option value="1" selected>1×</option><option value="2">2×</option></select></label><label>Tamaño <select id="size"><option value="96">96 px</option><option value="128" selected>128 px</option><option value="256">256 px</option><option value="native">Nativo</option></select></label><label><input id="single" type="checkbox" checked> Una vuelta</label><button id="dark" aria-pressed="false">Fondo oscuro</button></div><p id="status" class="steps" role="status"></p><div class="stage"><img id="sprite" alt=""></div><p id="purpose"></p><p id="timing" class="notes"></p><a id="download" class="download" download>Descargar WebP original</a><h2>Secuencia y duración de cada paso</h2><div id="timeline" class="timeline"></div><aside class="spec"><h2>Qué comprobar</h2><p>Cabeza y cuerpo registrados, una sola cola, objetos con tamaño estable, suelo fijo y retorno compatible al comienzo. “Una vuelta” se detiene al completar el ciclo; las acciones únicas conservan su último paso.</p><p><a href="../AUDITORIA-ORIGINALES.md">Observaciones por secuencia</a> · <a href="../rig-raster/index.html">Nuevas alternativas raster por capas</a></p></aside><footer>La galería entra pausada. Cambiar la preferencia a movimiento reducido o salir de la pestaña la detiene. El gato no acredita seguridad, liquidación ni rendimiento.</footer></div><script>
const catalog=${JSON.stringify(animations)},$=s=>document.querySelector(s),media=matchMedia('(prefers-reduced-motion:reduce)');
let current=catalog[0],elapsed=0,playing=false,ready=false,last=0,raf=0,selected=-1,revision=0,cycle=0;
window.__gpOriginalTrail=[];
function indexAt(ms){let limit=0;for(let i=0;i<current.sequence.length;i++){limit+=current.sequence[i].ms;if(ms<limit||i===current.sequence.length-1)return i}}
function paint(){const i=indexAt(elapsed),s=current.sequence[i];if(i!==selected){selected=i;$('#sprite').src=s.frame;$('#sprite').alt=current.name+', paso '+(i+1);$('#frame').value=i;document.querySelectorAll('#timeline button').forEach((b,n)=>b.setAttribute('aria-current',String(n===i)));window.__gpOriginalTrail.push({id:current.id,index:i,frame:s.frame,atMS:performance.now(),cycle});if(window.__gpOriginalTrail.length>256)window.__gpOriginalTrail.shift()}$('#status').textContent=current.name+' · '+(i+1)+'/'+current.sequence.length+' · '+Math.round(elapsed)+'/'+current.totalMs+' ms'+(cycle?' · ciclo '+cycle+' completado':'')}
function stop(){playing=false;cancelAnimationFrame(raf);last=0;$('#play').setAttribute('aria-pressed','false');$('#play').textContent='Reproducir'}
function tick(now){if(!playing)return;if(last)elapsed+=(now-last)*Number($('#speed').value);last=now;if(elapsed>=current.totalMs){cycle++;if(current.playback==='once'){elapsed=current.totalMs;paint();stop();return}elapsed%=current.totalMs;if($('#single').checked){elapsed=0;paint();stop();return}}paint();raf=requestAnimationFrame(tick)}
function step(i){stop();elapsed=current.sequence.slice(0,Math.min(current.sequence.length-1,Math.max(0,i))).reduce((n,s)=>n+s.ms,0);paint()}
function size(){const value=$('#size').value;$('.stage').style.setProperty('--size',(value==='native'?current.canvas.width:value)+'px')}
async function select(){const token=++revision;stop();ready=false;$('#play').disabled=true;current=catalog.find(a=>a.id===$('#action').value);elapsed=0;selected=-1;cycle=0;window.__gpOriginalTrail=[];$('#frame').max=current.sequence.length-1;$('#purpose').textContent=current.purpose;$('#timing').textContent=current.frames+' poses · '+current.sequence.length+' pasos · '+current.totalMs+' ms · '+(current.playback==='loop'?'loop':'una vez');$('#download').href=current.preview;$('#timeline').innerHTML=current.sequence.map((s,i)=>'<button data-step="'+i+'" aria-label="Paso '+(i+1)+' de '+current.name+'"><img src="'+s.frame+'" alt="">'+(i+1)+' · '+s.ms+' ms</button>').join('');size();paint();try{await Promise.all([...new Set(current.sequence.map(s=>s.frame))].map(src=>new Promise((ok,no)=>{const img=new Image();img.onload=ok;img.onerror=no;img.src=src})));if(token!==revision)return;ready=true;$('#play').disabled=false}catch(e){$('#status').textContent='No se pudieron cargar las imágenes'}}
$('#action').addEventListener('change',select);$('#play').addEventListener('click',()=>{if(playing){stop();return}if(!ready)return;if(elapsed===current.totalMs||cycle){elapsed=0;cycle=0;selected=-1;window.__gpOriginalTrail=[];paint()}playing=true;last=0;$('#play').setAttribute('aria-pressed','true');$('#play').textContent='Pausar';raf=requestAnimationFrame(tick)});$('#reset').addEventListener('click',()=>{cycle=0;window.__gpOriginalTrail=[];selected=-1;step(0)});$('#prev').addEventListener('click',()=>step(selected-1));$('#next').addEventListener('click',()=>step(selected+1));$('#frame').addEventListener('input',e=>step(Number(e.target.value)));$('#timeline').addEventListener('click',e=>{const b=e.target.closest('[data-step]');if(b)step(Number(b.dataset.step))});$('#size').addEventListener('change',size);$('#dark').addEventListener('click',e=>{const active=$('.stage').classList.toggle('dark');e.target.setAttribute('aria-pressed',String(active));e.target.textContent=active?'Fondo claro':'Fondo oscuro'});media.addEventListener('change',e=>{if(e.matches)stop()});document.addEventListener('visibilitychange',()=>{if(document.hidden)stop()});select();
</script></body></html>`;
await writeFile(join(root,'index.html'),html);
console.log(JSON.stringify({sequences:animations.length,uniquePoses:animations.reduce((n,a)=>n+a.frames,0),steps:animations.reduce((n,a)=>n+a.sequence.length,0),sourceSHA256:hash(source),html:'01-animaciones/originales/index.html'}));
