import {readFile,writeFile,mkdir} from 'node:fs/promises';
import {resolve,dirname,join} from 'node:path';
import {fileURLToPath} from 'node:url';
import {createHash} from 'node:crypto';
import sharp from 'sharp';
const lab=resolve(dirname(fileURLToPath(import.meta.url)),'..'),root=join(lab,'01-animaciones/rig-acciones');
const originals=JSON.parse(await readFile(join(lab,'01-animaciones/originales/catalogo.json'),'utf8'));
const sha=b=>createHash('sha256').update(b).digest('hex');
const layers={};await mkdir(join(root,'capas'),{recursive:true});
function bounds(r){let x0=r.info.width,y0=r.info.height,x1=-1,y1=-1;for(let y=0;y<r.info.height;y++)for(let x=0;x<r.info.width;x++)if(r.data[(y*r.info.width+x)*4+3]>24){x0=Math.min(x0,x);y0=Math.min(y0,y);x1=Math.max(x1,x);y1=Math.max(y1,y);}return{x0,y0,x1,y1};}
async function layer(name,png,source){const raw=await sharp(png).ensureAlpha().raw().toBuffer({resolveWithObject:true}),file='capas/'+name+'.png';await writeFile(join(root,file),png);const L={name,file,sha256:sha(png),width:raw.info.width,height:raw.info.height,bounds:bounds(raw),source,dataURI:'data:image/png;base64,'+png.toString('base64'),raw};layers[name]=L;return L;}
const plateFile='01-animaciones/fuentes/caminata-capas-v1.png',plate=await readFile(join(lab,plateFile)),r=await sharp(plate).ensureAlpha().raw().toBuffer({resolveWithObject:true});
function gutter(axis){const mid=Math.floor((axis==='x'?r.info.width:r.info.height)/2);for(let d=0;d<100;d++)for(const p of[mid-d,mid+d]){let any=false;for(let k=0;k<(axis==='x'?r.info.height:r.info.width);k++){const x=axis==='x'?p:k,y=axis==='x'?k:p;if(r.data[(y*r.info.width+x)*4+3]){any=true;break;}}if(!any)return p;}throw Error('No hay separación alfa cero '+axis);}
const gx=gutter('x'),gy=gutter('y');
async function cell(name,left,top,width,height){const rect={left,top,width,height};return layer(name,await sharp(plate).extract(rect).png().toBuffer(),{file:plateFile,sha256:sha(plate),cell:rect,method:'celdas separadas en gutters alfa cero; píxeles y padding conservados'});}
const upper=await cell('mensajero-sin-patas',0,0,gx,gy),far=await cell('pata-lejana',gx,0,r.info.width-gx,gy),near=await cell('pata-cercana',0,gy,gx,r.info.height-gy);
const workerFile='01-animaciones/fuentes/mantenimiento-cuerpo-v1.png',workerPNG=await readFile(join(lab,workerFile));
const worker=await layer('cuerpo-con-casco',workerPNG,{file:workerFile,sha256:sha(workerPNG),method:'PNG generado completo, sin recorte ni retoque; referencia del cuerpo-rail y casco original'});
const pawFile='01-animaciones/rig-raster/capas/pata-rail.png',pawPNG=await readFile(join(lab,pawFile));
const paw=await layer('pata-herramienta',pawPNG,{file:pawFile,sha256:sha(pawPNG),method:'copia exacta de la pieza raster separada de rail-capas-v2'});
async function native(name,width,height,inner){const file='01-animaciones/rig-acciones/capas/'+name+'-fuente.svg',svg=`<svg xmlns="http://www.w3.org/2000/svg" width="${width}" height="${height}" viewBox="0 0 ${width} ${height}">${inner}</svg>`;await writeFile(join(lab,file),svg);return layer(name,await sharp(Buffer.from(svg)).png().toBuffer(),{file,sha256:sha(Buffer.from(svg)),renderedSVG:true,method:'objeto geométrico original en SVG; el personaje sigue siendo raster'});}
const rail=await native('rail-continuo',560,36,'<rect width="560" height="36" fill="#0b0b0f"/><rect x="4" y="4" width="552" height="28" fill="#68717f"/><path fill="#ffc55b" d="M36 4H48V32H36ZM108 4H120V32H108ZM180 4H192V32H180ZM252 4H264V32H252ZM324 4H336V32H324ZM396 4H408V32H396ZM468 4H480V32H468ZM540 4H552V32H540Z"/>');
const signal=await native('senal-ruta',16,16,'<rect width="16" height="16" fill="#f85239"/>');
const hammer=await native('martillo',56,88,'<path fill="#0b0b0f" d="M22 0H34V60H56V88H0V60H22Z"/><path fill="#d9972c" d="M26 4H30V64H26Z"/><rect x="4" y="64" width="48" height="20" fill="#68717f"/><path fill="#fff8f0" d="M4 64H52V68H4Z"/>');
function attachment(L){let sum=0,n=0;for(let y=L.bounds.y0;y<L.bounds.y0+14;y++)for(let x=0;x<L.width;x++)if(L.raw.data[(y*L.width+x)*4+3]>24){sum+=x;n++;}return{x:sum/n,y:L.bounds.y0+10};}
const anchors=[attachment(far),attachment(near)],legScales=[92/(far.bounds.y1-anchors[0].y),92/(near.bounds.y1-anchors[1].y)];
const bodyScale=.7,bodyHip={x:[313,395],y:548},bodyX=384-(313+395)/2*bodyScale,groundY=512;
const points=[far,near].map((L,j)=>{const out=[];for(let y=0;y<L.height;y++)for(let x=0;x<L.width;x++)if(L.raw.data[(y*L.width+x)*4+3]>24)out.push({x:(x-anchors[j].x)*legScales[j],y:(y-anchors[j].y)*legScales[j]});return out;});
const clean=n=>Math.abs(n)<1e-10?0:n;
function gait(t){const a=clean(26*Math.cos(t*2*Math.PI)),angles=[a,-a],s=clean(Math.sin(t*2*Math.PI)),lifts=[12*Math.max(0,s),12*Math.max(0,-s)];const depths=points.map((P,j)=>Math.max(...P.map(p=>p.x*Math.sin(angles[j]*Math.PI/180)+p.y*Math.cos(angles[j]*Math.PI/180)-lifts[j])));const hipY=groundY-Math.max(...depths);return{angles,lifts,depths,hipY,bodyY:hipY-bodyHip.y*bodyScale};}
const img=(id,L,x,y,s=1)=>`<image id="${id}" href="${L.dataURI}" x="${clean(x).toFixed(3)}" y="${clean(y).toFixed(3)}" width="${(L.width*s).toFixed(3)}" height="${(L.height*s).toFixed(3)}"/>`;
function walker(t){const G=gait(t);return [far,near].map((L,j)=>{const hipX=bodyX+bodyHip.x[j]*bodyScale;return `<g id="leg-${j}" transform="translate(0 ${(-G.lifts[j]).toFixed(4)}) rotate(${G.angles[j].toFixed(4)} ${hipX.toFixed(3)} ${G.hipY.toFixed(3)})">${img('leg-'+j+'-image',L,hipX-anchors[j].x*legScales[j],G.hipY-anchors[j].y*legScales[j],legScales[j])}</g>`;}).join('')+`<g id="upper">${img('upper-image',upper,bodyX,G.bodyY,bodyScale)}</g>`;}
const workScale=887/worker.width*.5,workX=60,workY=495-worker.bounds.y1*workScale;
const shoulder={x:workX+520*.5,y:workY+560*.5},pawX=shoulder.x-(paw.bounds.x0+20)*.5,pawY=shoulder.y-(paw.bounds.y0+36)*.5;
const grip={x:pawX+(paw.bounds.x1-24)*.5,y:pawY+(paw.bounds.y1-24)*.5};
const hammerX=grip.x-28,hammerY=495-88;
const imageSources={'leg-0-image':far.name,'leg-1-image':near.name,'upper-image':upper.name,'rail-image':rail.name,'signal-image':signal.name,'hammer-image':hammer.name,'paw-image':paw.name,'worker-image':worker.name};
const defs=[
 {id:'caminata',name:'Caminata',count:61,ms:()=>20,prompt:'../prompts/caminata-capas-v1.txt',correction:'Perfil y paquete constantes, una sola cola; las dos patas alternan el apoyo. El cuerpo se ajusta al contacto real de las patas con un suelo fijo, en vez de cambiar de dibujo o flotar.',draw:t=>walker(t)},
 {id:'preparando-pago',name:'Preparando el pago',count:61,ms:()=>25,prompt:'preparando-pago/reglas.json',correction:'Preparación sin confeti ni mensaje de éxito: el mismo mensajero camina sobre un rail fijo. Una señal discreta avanza por el rail y se desvanece antes de reiniciar. No indica porcentaje ni confirma el pago.',draw:t=>{const opacity=t<.15?t/.15:t>.85?(1-t)/.15:1;return `<g id="rail">${img('rail-image',rail,96,512)}</g><g id="signal" opacity="${clean(opacity).toFixed(5)}">${img('signal-image',signal,100+536*t,522)}</g>`+walker(t);}},
 {id:'mantenimiento',name:'Mantenimiento',count:61,ms:i=>i===0||i===60?500:35,prompt:'../prompts/mantenimiento-cuerpo-v1.txt',correction:'Cuerpo, cabeza, casco y rail fijos. La misma pata sostiene un martillo y hace dos golpes pequeños con pausa. La herramienta vuelve a su reposo sin cambiar de tamaño, ni convertir la acción en una celebración.',draw:t=>{const angle=clean(-12*(1+Math.cos(4*Math.PI*t))),transform=`rotate(${angle.toFixed(4)} ${shoulder.x.toFixed(3)} ${shoulder.y.toFixed(3)})`;return `<g id="rail">${img('rail-image',rail,96,495)}</g><g id="hammer" transform="${transform}">${img('hammer-image',hammer,hammerX,hammerY)}</g><g id="paw" transform="${transform}">${img('paw-image',paw,pawX,pawY,.5)}</g><g id="worker">${img('worker-image',worker,workX,workY,workScale)}</g>`;}}
];
const records=[];
for(const d of defs){const dir=join(root,d.id);for(const sub of['fotogramas','miniaturas'])await mkdir(join(dir,sub),{recursive:true});const sequence=[],rgba=[],geometry=[];
 for(let i=0;i<d.count;i++){const t=i/(d.count-1),markup=d.draw(t),svg=`<svg xmlns="http://www.w3.org/2000/svg" width="768" height="640" viewBox="0 0 768 640" role="img" aria-label="${d.name}, montaje raster"><title>${d.name}: paso ${i+1}</title>${markup}</svg>`,png=await sharp(Buffer.from(svg)).png().toBuffer(),num=String(i+1).padStart(2,'0'),frame=d.id+'/fotogramas/'+num+'.png',thumbnail=d.id+'/miniaturas/'+num+'.png';await writeFile(join(root,frame),png);await sharp(png).resize(160,133,{fit:'fill',kernel:'nearest'}).png().toFile(join(root,thumbnail));sequence.push({frame,thumbnail,ms:d.ms(i),phase:t,sha256:sha(png)});rgba.push(await sharp(png).ensureAlpha().raw().toBuffer());geometry.push({step:i+1,groups:[...markup.matchAll(/<g[^>]+>/g)].map(m=>m[0]),images:[...markup.matchAll(/<image id="([^"]+)"[^>]+x="([^"]+)" y="([^"]+)" width="([^"]+)" height="([^"]+)"\/>/g)].map(m=>({id:m[1],x:Number(m[2]),y:Number(m[3]),width:Number(m[4]),height:Number(m[5])})),gait:d.id!=='mantenimiento'?gait(t):undefined});if(i===0)await writeFile(join(dir,'escena.svg'),svg);}
 const preview=d.id+'/'+d.id+'-capas-v1.webp';await sharp(Buffer.concat(rgba),{raw:{width:768,height:640*d.count,channels:4,pageHeight:640}}).webp({lossless:true,loop:0,delay:sequence.map(s=>s.ms)}).toFile(join(root,preview));
 const samples=Array.from({length:9},(_,i)=>Math.round(i*(d.count-1)/8)),tiles=await Promise.all(samples.map(i=>sharp(join(root,sequence[i].frame)).resize(256,213,{fit:'fill',kernel:'nearest'}).png().toBuffer()));await sharp({create:{width:768,height:639,channels:4,background:'#fff8f0'}}).composite(tiles.map((input,i)=>({input,left:i%3*256,top:Math.floor(i/3)*213}))).png().toFile(join(dir,'hoja-normalizada.png'));
 const ref=originals.animations.find(a=>a.id===d.id);if(!ref)throw Error('Sin referencia '+d.id);
 const record={id:d.id,name:d.name,status:'candidato raster por capas; sin aprobación artística final',method:'piezas image_gen integradas, PNG reutilizados y objetos SVG originales; montaje mecánico con sharp',source:d.id+'/escena.svg',sourceSHA256:sha(await readFile(join(dir,'escena.svg'))),prompt:d.prompt,canvas:{width:768,height:640},frames:d.count,totalMs:sequence.reduce((n,s)=>n+s.ms,0),playback:'loop',preview,sequence,original:ref,correction:d.correction,knownLimit:'El SVG compone PNG: no es un gato vectorizado. Las piezas generadas difieren del dibujo de partida y las patas se articulan rígidamente. El paquete y la cola permanecen fijos en la caminata; no se afirma una caminata anatómicamente dibujada frame a frame. El martillo es un objeto nuevo. Requiere revisión artística, sin sustituir archivos del kit ni afirmar progreso financiero.',imageSources,geometry};
 await writeFile(join(dir,'manifest.json'),JSON.stringify(record,null,2));await writeFile(join(dir,'reglas.json'),JSON.stringify({correction:d.correction,generator:'tools/raster-actions.mjs',groundY,bodyScale,bodyHip,bodyX,anchors,legScales,workScale,workX,workY,shoulder,grip,hammerX,hammerY,railTop:495,originalsUnmodified:true},null,2));records.push(record);
}
await writeFile(join(root,'capas.json'),JSON.stringify({layers:Object.values(layers).map(({raw,dataURI,...L})=>L)},null,2));
await writeFile(join(root,'comparativas.json'),JSON.stringify({status:'tres candidatos adicionales; sin modificar brandkit',animations:records.map(({geometry,...a})=>a)},null,2));
await writeFile(join(root,'README.md'),'# Tres acciones adicionales\n\nCaminata, preparando pago y mantenimiento: 183 PNG completos, 183 miniaturas, tres WebP lossless, hojas de nueve muestras y escenas SVG con PNG incrustados. No son personajes vectorizados. Las celdas de la caminata conservan todos los píxeles y padding, separados en gutters alfa cero; el casco se añadió con image_gen a una nueva fuente, sin retocar el kit. Prompts y fuentes en las carpetas vecinas.\n\nLas patas alternan su giro y elevación; el apoyo define el movimiento vertical del cuerpo sobre un suelo fijo. La preparación no afirma éxito ni porcentaje. El casco y cuerpo de mantenimiento no se redibujan; la herramienta y pata giran conjuntamente. Consultar `REVISION.md` y `.qa/raster-actions/` para distinguir comprobaciones de aprobación artística.\n');
console.log(JSON.stringify({actions:records.length,frames:183,layers:Object.keys(layers).length,gutters:{x:gx,y:gy},anchors,legScales,workScale,shoulder,grip,root}));
