import {readFile,writeFile,mkdir} from 'node:fs/promises';
import {resolve,dirname,join} from 'node:path';
import {fileURLToPath} from 'node:url';
import {createHash} from 'node:crypto';
import sharp from 'sharp';
const lab=resolve(dirname(fileURLToPath(import.meta.url)),'..'),root=join(lab,'01-animaciones/rig-documento');
const hash=b=>createHash('sha256').update(b).digest('hex');
await mkdir(join(root,'comprobante/fotogramas'),{recursive:true});await mkdir(join(root,'comprobante/miniaturas'),{recursive:true});
const file='01-animaciones/fuentes/comprobante-cuerpo-v2.png',body=await readFile(join(lab,file)),headFile='01-animaciones/rig-gestos/capas/cabeza-sentada.png',head=await readFile(join(lab,headFile));
const raw=await sharp(body).ensureAlpha().raw().toBuffer({resolveWithObject:true}),hm=await sharp(head).metadata();
const b={x0:raw.info.width,y0:raw.info.height,x1:-1,y1:-1},paper={x0:raw.info.width,y0:raw.info.height,x1:-1,y1:-1};
for(let y=0;y<raw.info.height;y++)for(let x=0;x<raw.info.width;x++){const i=(y*raw.info.width+x)*4,[r,g,blue,a]=raw.data.subarray(i,i+4);if(a>24){b.x0=Math.min(x,b.x0);b.x1=Math.max(x,b.x1);b.y0=Math.min(y,b.y0);b.y1=Math.max(y,b.y1);}if(a>240&&r>205&&g>205&&blue>195){paper.x0=Math.min(x,paper.x0);paper.x1=Math.max(x,paper.x1);paper.y0=Math.min(y,paper.y0);paper.y1=Math.max(y,paper.y1);}}
if(paper.x1<=paper.x0||paper.y1<=paper.y0)throw Error('Papel claro ausente');
// Las coordenadas sirven para colocar el PNG completo; nunca para recortar/recolorear el gato.
const scale=.4,ground=560,bodyX=384-(paper.x0+paper.x1)/2*scale,bodyY=ground-b.y1*scale;
const headX=140.4,headY=54.4,headScale=.6;
const safe={x:bodyX+(paper.x0+(paper.x1-paper.x0)*.2)*scale,y:bodyY+(paper.y0+24)*scale,width:(paper.x1-paper.x0)*.6*scale,height:(paper.y1-paper.y0-48)*scale};
const bodyTag=`<image id="body-paper" href="data:image/png;base64,${body.toString('base64')}" x="${bodyX}" y="${bodyY}" width="${raw.info.width*scale}" height="${raw.info.height*scale}"/>`,headTag=`<image id="head" href="data:image/png;base64,${head.toString('base64')}" x="${headX}" y="${headY}" width="${hm.width*headScale}" height="${hm.height*headScale}"/>`;
const clamp=t=>Math.max(0,Math.min(1,t)),ease=t=>{t=clamp(t);return t*t*(3-2*t);};
export function inkMarkup(t,S=safe){const x=S.x,y=S.y,w=S.width,h=S.height,f=n=>n.toFixed(4),length=w*.68*Math.SQRT2;const line=(j,q,span)=>`<rect id="line-${j}" x="${f(x)}" y="${f(y+j*14)}" width="${f(w*span*ease(q))}" height="4" fill="#0b0b0f"/>`;return '<g id="ink">'+line(0,(t-.08)/.25,1)+line(1,(t-.2)/.25,.78)+line(2,(t-.32)/.25,.58)+`<path id="receipt-detail" d="M${f(x+w*.16)} ${f(y+h*.69)}l${f(w*.2)} ${f(w*.2)}l${f(w*.48)} -${f(w*.48)}" fill="none" stroke="#0b0b0f" stroke-width="5" stroke-linecap="square" stroke-linejoin="miter" opacity="${f(ease((t-.58)/.06))}" stroke-dasharray="${f(length)}" stroke-dashoffset="${f(length*(1-ease((t-.58)/.27)))}"/>`+'</g>';}
const sequence=[],rgba=[],geometry=[];
for(let i=0;i<61;i++){const phase=i/60,ink=inkMarkup(phase),svg=`<svg xmlns="http://www.w3.org/2000/svg" width="768" height="640" viewBox="0 0 768 640"><title>Comprobante ilustrado, paso ${i+1}</title>${bodyTag}${headTag}${ink}</svg>`,png=await sharp(Buffer.from(svg)).png().toBuffer(),num=String(i+1).padStart(2,'0'),frame='comprobante/fotogramas/'+num+'.png',thumbnail='comprobante/miniaturas/'+num+'.png';await writeFile(join(root,frame),png);await sharp(png).resize(160,133,{kernel:'nearest',fit:'fill'}).png().toFile(join(root,thumbnail));const ms=i===0?400:i===60?1000:20;sequence.push({frame,thumbnail,ms,phase,sha256:hash(png)});rgba.push(await sharp(png).ensureAlpha().raw().toBuffer());geometry.push({step:i+1,ink});if(i===0)await writeFile(join(root,'comprobante/escena.svg'),svg);}
const preview='comprobante/comprobante-capas-v1.webp';await sharp(Buffer.concat(rgba),{raw:{width:768,height:640*61,channels:4,pageHeight:640}}).webp({lossless:true,loop:1,delay:sequence.map(s=>s.ms)}).toFile(join(root,preview));
const cells=await Promise.all(Array.from({length:9},(_,i)=>Math.round(i*60/8)).map(i=>sharp(join(root,sequence[i].frame)).resize(256,213,{fit:'fill',kernel:'nearest'}).png().toBuffer()));await sharp({create:{width:768,height:639,channels:4,background:'#fff8f0'}}).composite(cells.map((input,i)=>({input,left:i%3*256,top:Math.floor(i/3)*213}))).png().toFile(join(root,'comprobante/hoja-normalizada.png'));
const original=JSON.parse(await readFile(join(lab,'01-animaciones/originales/catalogo.json'),'utf8')).animations.find(a=>a.id==='comprobante');
const record={id:'comprobante',name:'Comprobante ilustrado',status:'candidato raster independiente, sin aprobación artística final',method:'dos PNG raster constantes y detalle nativo SVG en el papel',source:'comprobante/escena.svg',sourceSHA256:hash(await readFile(join(root,'comprobante/escena.svg'))),prompt:'../prompts/comprobante-cuerpo-v2.txt',canvas:{width:768,height:640},frames:61,totalMs:sequence.reduce((n,s)=>n+s.ms,0),playback:'once',preview,sequence,original,correction:'Una cabeza y un cuerpo/papel raster constantes. El documento no cambia de tamaño, las patas no se redibujan y no aparece un utensilio nuevo. Tres líneas y un detalle se dibujan una vez dentro del papel; el último estado queda visible.',knownLimit:'Gato sentado con papel, no una animación de firma dibujada. Las cuatro extremidades se comprobaron visualmente, no mediante un detector anatómico. La base generada puede diferir del original. El detalle del documento es ilustrativo: no prueba pago, firma, identidad ni liquidación. No se instala en la app.',sources:[{file,sha256:hash(body),width:raw.info.width,height:raw.info.height},{file:headFile,sha256:hash(head),width:hm.width,height:hm.height}],rules:{ground,scale,bodyX,bodyY,headX,headY,headScale,paper,safe,bounds:b,bodyTag,headTag},geometry};
await writeFile(join(root,'comprobante/manifest.json'),JSON.stringify(record,null,2));await writeFile(join(root,'comparativas.json'),JSON.stringify({status:'comprobante candidato con raster constante',animations:[(({geometry,rules,...a})=>a)(record)]},null,2));
console.log(JSON.stringify({actions:1,frames:61,totalMs:record.totalMs,paper,safe,body:{x:bodyX,y:bodyY,scale},bounds:b}));
