import {readFile,writeFile,mkdir} from 'node:fs/promises';
import {resolve,dirname,join} from 'node:path';
import {fileURLToPath} from 'node:url';
import {createHash} from 'node:crypto';
import sharp from 'sharp';
const lab=resolve(dirname(fileURLToPath(import.meta.url)),'..'),root=join(lab,'01-animaciones/rig-revision');
const sha=b=>createHash('sha256').update(b).digest('hex'),W=768,H=640;
const prior=JSON.parse(await readFile(join(lab,'01-animaciones/rig-raster/comparativas.json'),'utf8'));
const layers={};
function bounds(r){let x0=r.info.width,y0=r.info.height,x1=-1,y1=-1;for(let y=0;y<r.info.height;y++)for(let x=0;x<r.info.width;x++)if(r.data[(y*r.info.width+x)*4+3]>24){x0=Math.min(x0,x);y0=Math.min(y0,y);x1=Math.max(x1,x);y1=Math.max(y1,y);}return{x0,y0,x1,y1};}
async function layer(id,png,source){const raw=await sharp(png).ensureAlpha().raw().toBuffer({resolveWithObject:true});const L={id,width:raw.info.width,height:raw.info.height,bounds:bounds(raw),file:'capas/'+id+'.png',sha256:sha(png),source,uri:'data:image/png;base64,'+png.toString('base64')};await mkdir(join(root,'capas'),{recursive:true});await writeFile(join(root,L.file),png);layers[id]=L;return L;}
async function old(id){return layer(id,await readFile(join(lab,'01-animaciones/rig-raster/capas',id+'.png')),{file:'01-animaciones/rig-raster/capas/'+id+'.png',method:'copia íntegra, sin retoques'});}
const peek=await layer('asomarse-cuerpo',await readFile(join(root,'fuentes/asomarse-cuerpo-v2.png')),{file:'fuentes/asomarse-cuerpo-v2.png',method:'image_gen integrado; personaje completo, alfa original'});
const plate=await readFile(join(root,'fuentes/intercambio-capas-v3.png')),raw=await sharp(plate).ensureAlpha().raw().toBuffer({resolveWithObject:true});
let gutter=-1;for(let x=Math.floor(raw.info.width*.59);x<raw.info.width*.72;x++){if(Array.from({length:raw.info.height},(_,y)=>raw.data[(y*raw.info.width+x)*4+3]).every(a=>a===0)){gutter=x;break;}}
if(gutter<0)throw Error('La placa no tiene un gutter alfa cero; no se permite cortar la silueta');
const source={file:'fuentes/intercambio-capas-v3.png',sha256:sha(plate),method:'separación en columna alfa cero; no recolorea ni redibuja'};
const swapBody=await layer('intercambio-cuerpo',await sharp(plate).extract({left:0,top:0,width:gutter,height:raw.info.height}).png().toBuffer(),{...source,cell:{left:0,top:0,width:gutter,height:raw.info.height}});
const swapPaw=await layer('intercambio-pata',await sharp(plate).extract({left:gutter,top:0,width:raw.info.width-gutter,height:raw.info.height}).png().toBuffer(),{...source,cell:{left:gutter,top:0,width:raw.info.width-gutter,height:raw.info.height}});
const card=await old('tarjeta-asomarse'),worker=await old('cuerpo-rail'),paw=await old('pata-rail'),rail=await old('rail-fijo'),piece=await old('pieza-rail');
const img=(L,x,y,s=1)=>`<image data-layer="${L.id}" href="${L.uri}" x="${x.toFixed(3)}" y="${y.toFixed(3)}" width="${(L.width*s).toFixed(3)}" height="${(L.height*s).toFixed(3)}" style="image-rendering:pixelated"/>`;
const clamp=t=>Math.max(0,Math.min(1,t)),ease=t=>{t=clamp(t);return t*t*(3-2*t);},between=(t,a,b)=>ease((t-a)/(b-a));
const sparkle=(x,y,size,opacity=1)=>`<g opacity="${opacity.toFixed(4)}" transform="translate(${x} ${y}) scale(${size})"><path fill="#ffc55b" d="M-1-5H1V-2H2V-1H5V1H2V2H1V5H-1V2H-2V1H-5V-1H-2V-2H-1Z"/><path fill="#fff8f0" d="M-1-1H1V1H-1Z"/></g>`;
const check=(x,y,opacity)=>`<g id="signo" opacity="${opacity.toFixed(4)}" transform="translate(${x} ${y})"><path fill="#0b0b0f" d="M-28-20H20V-12H28V20H20V28H-28Z"/><path fill="#fff8f0" d="M-24-16H16V-8H24V16H16V24H-24Z"/><path fill="#9f292e" d="M-14 0H-6V8H2V0H10V-8H18V0H10V8H2V16H-6V8H-14Z"/></g>`;
function block(x,y,color){const blue=color==='blue',fill=blue?'#4169b1':'#ffc55b',shade=blue?'#274779':'#d9972c';return `<g transform="translate(${x.toFixed(3)} ${y.toFixed(3)})"><path fill="#0b0b0f" d="M0 0H92L108 16V104H16L0 88Z"/><path fill="${fill}" d="M4 4H88V88H4Z"/><path fill="${shade}" d="M92 8L104 20V100H20L8 92H92Z"/>${blue?'<path fill="#fff8f0" d="M24 24H68V58H48L36 70V58H24ZM32 32V50H60V32Z"/><path fill="#fff8f0" d="M38 38H44V44H38ZM50 38H56V44H50Z"/>':'<path fill="#9f292e" d="M24 28H36V40H56V28H68V64H24Z"/>'}</g>`;}
const railPivot={x:424-120*Math.cos(24*Math.PI/180),y:479-18-120*Math.sin(24*Math.PI/180)};
const workerScale=.5,workerX=railPivot.x-520*workerScale,workerY=railPivot.y-560*workerScale;
const pawX=railPivot.x-(paw.bounds.x0+20)*workerScale,pawY=railPivot.y-(paw.bounds.y0+36)*workerScale;
const peekScale=.27,peekY=123-peek.bounds.y0*peekScale;
const hiddenX=364-(peek.bounds.x1+1)*peekScale,shownX=320-peek.bounds.x0*peekScale;
const swapScale=.48,bodyX=176-swapBody.bounds.x0*swapScale,bodyY=156-swapBody.bounds.y0*swapScale;
// A stable shoulder attachment; the raster forepaw turns from this point, not from its centre.
const shoulder={x:bodyX+688*swapScale,y:bodyY+640*swapScale};
const armX=shoulder.x-(swapPaw.bounds.x0+20)*swapScale,armY=shoulder.y-(swapPaw.bounds.y0+40)*swapScale;
const defs=[
 {id:'asomarse',count:97,ms:i=>i===0?500:i===96?650:45,prompt:'prompts/asomarse-v2.txt',correction:'La cabeza da paso al torso, las patas y una sola cola. Hay una pausa para mirar y un regreso completo detrás de la misma tarjeta original. Se conserva el cuerpo completo como fuente, sin recortar orejas o cola.',stages:['oculta','primera mirada','sale el cuerpo','pausa curiosa','vuelve a esconderse'],draw:t=>{let reveal=t<.32?.62*between(t,.08,.32):t<.52?.62+.38*between(t,.32,.52):t<.72?1:1-between(t,.72,1);const x=hiddenX+(shownX-hiddenX)*reveal;const lean=t>.52&&t<.72?1.8*Math.sin((t-.52)/.2*Math.PI):0;return {state:{reveal,bodyVisible:reveal>.85,fullyHidden:reveal===0},markup:`<defs><clipPath id="panel-occlusion"><rect x="364" y="70" width="360" height="490"/></clipPath></defs><g id="gato" clip-path="url(#panel-occlusion)"><g transform="rotate(${lean.toFixed(3)} 392 358)">${img(peek,x,peekY,peekScale)}</g></g><g id="tarjeta">${img(card,160,80,2)}</g>`};}},
 {id:'reparar-rail',count:121,ms:i=>i===0?400:i===120?850:40,prompt:'reparar-rail/reglas.json',correction:'La pata baja la pieza, ajusta el encaje y se retira. El brillo aparece después del encaje; luego un signo discreto y una flecha recorren el camino restaurado. El hueco conserva su tamaño exacto y no vuelve a abrirse al terminar.',stages:['prepara','baja la pieza','encaja','retira la pata','brillo','signo','recorre la flecha','final estable'],draw:t=>{const seat=between(t,.06,.48),angle=-28+52*seat,r=angle*Math.PI/180;const x=seat===1?376:railPivot.x+120*Math.cos(r)-48,y=seat===1?479:railPivot.y+120*Math.sin(r)+18;const withdrawal=between(t,.50,.66),armAngle=angle-12*withdrawal;const glow=t>=.48&&t<.74?Math.sin(clamp((t-.48)/.26)*Math.PI):0,sign=between(t,.69,.79),progress=between(t,.76,.95),arrowOpacity=t<.76?0:t<.95?1:1-between(t,.95,1);const arrowX=405+208*progress;return {state:{seat,x,y,armAngle,glow,sign,arrowX,arrowOpacity},markup:`<g id="rail">${img(rail,96,479)}</g><g id="pieza">${img(piece,x,y)}</g><g id="pata" transform="rotate(${armAngle.toFixed(4)} ${railPivot.x.toFixed(3)} ${railPivot.y.toFixed(3)})">${img(paw,pawX,pawY,workerScale)}</g><g id="gato">${img(worker,workerX,workerY,workerScale)}</g><g id="brillo">${sparkle(495,435,3.2,glow)}${sparkle(458,407,1.6,glow)}${sparkle(528,461,1.6,glow)}</g>${check(574,407,sign)}<g id="flecha" opacity="${arrowOpacity.toFixed(4)}" transform="translate(${arrowX.toFixed(3)} 448)"><path fill="#f85239" d="M-18-5H2V-13H10V-5H18V3H10V11H2V3H-18Z"/></g>`};}},
 {id:'intercambio',count:109,ms:i=>i===0?500:i===108?900:40,prompt:'prompts/intercambio-boca-v3.txt',correction:'Se abandona la órbita alrededor de una mascota sentada. El gato está de pie, toca un bloque con su pata y se inclina al empujarlo. Dos bloques con volumen intercambian lugares junto a él mediante recorridos cortos, con flechas y un brillo de cierre.',stages:['mira los bloques','acerca la pata','empuja','intercambian posiciones','retira la pata','brillo breve','final estable'],draw:t=>{const push=between(t,.12,.28)*(1-between(t,.65,.82)),q=between(t,.28,.65),bob=-4*Math.sin(q*Math.PI),dx=16*push;const armAngle=-8+18*push;const gx=440+136*q,gy=423-126*Math.sin(q*Math.PI),bx=576-136*q,by=423+54*Math.sin(q*Math.PI);const arrows=t>.24&&t<.72?Math.sin(clamp((t-.24)/.48)*Math.PI):0;const glow=t>.77&&t<.95?Math.sin((t-.77)/.18*Math.PI):0;const arrowMarkup=`<g id="flechas" opacity="${arrows.toFixed(4)}"><path d="M468 336H544V346M530 346H544V332M548 554H470V544M484 544H470V558" stroke="#0b0b0f" stroke-width="5" fill="none"/></g>`;return {state:{push,q,bodyShift:dx,armAngle,gold:{x:gx,y:gy},blue:{x:bx,y:by},arrows,glow},markup:`<g id="gato" transform="translate(${dx.toFixed(3)} ${bob.toFixed(3)})">${img(swapBody,bodyX,bodyY,swapScale)}<g id="pata" transform="rotate(${armAngle.toFixed(3)} ${shoulder.x.toFixed(3)} ${shoulder.y.toFixed(3)})">${img(swapPaw,armX,armY,swapScale)}</g></g>${arrowMarkup}<g id="dorado">${block(gx,gy,'gold')}</g><g id="azul">${block(bx,by,'blue')}</g><g id="brillo">${sparkle(541,365,3,glow)}${sparkle(660,394,1.7,glow)}</g>`};}}
];
const records=[];
for(const d of defs){const dir=join(root,d.id);for(const sub of ['fotogramas','miniaturas'])await mkdir(join(dir,sub),{recursive:true});const sequence=[],rgba=[],states=[];
 for(let i=0;i<d.count;i++){const t=i/(d.count-1),{markup,state}=d.draw(t),svg=`<svg xmlns="http://www.w3.org/2000/svg" width="${W}" height="${H}" viewBox="0 0 ${W} ${H}"><title>${d.id} · revisión · paso ${i+1}</title>${markup}</svg>`;const png=await sharp(Buffer.from(svg)).png().toBuffer(),n=String(i+1).padStart(3,'0'),frame=d.id+'/fotogramas/'+n+'.png',thumbnail=d.id+'/miniaturas/'+n+'.png';await writeFile(join(root,frame),png);await sharp(png).resize(160,133,{fit:'fill',kernel:'nearest'}).png().toFile(join(root,thumbnail));sequence.push({frame,thumbnail,ms:d.ms(i),phase:t,sha256:sha(png)});rgba.push(await sharp(png).ensureAlpha().raw().toBuffer());states.push({step:i+1,...state});if(i===0)await writeFile(join(dir,'escena.svg'),svg);}
 const preview=d.id+'/'+d.id+'-revision-v2.webp';await sharp(Buffer.concat(rgba),{raw:{width:W,height:H*d.count,channels:4,pageHeight:H}}).webp({lossless:true,delay:sequence.map(s=>s.ms),loop:1}).toFile(join(root,preview));
 const chosen=Array.from({length:12},(_,i)=>Math.round(i*(d.count-1)/11)),thumbs=await Promise.all(chosen.map(i=>sharp(join(root,sequence[i].frame)).resize(256,213,{kernel:'nearest'}).png().toBuffer()));await sharp({create:{width:1024,height:639,channels:4,background:'#fff8f0'}}).composite(thumbs.map((input,i)=>({input,left:(i%4)*256,top:Math.floor(i/4)*213}))).png().toFile(join(dir,'hoja-normalizada.png'));
 const ref=prior.animations.find(a=>a.id===d.id).original;
 const record={id:d.id,status:'revisión del feedback; candidato separado del kit, pendiente de aprobación visual',method:'image_gen integrado para personajes; movimiento determinista por capas PNG; objetos y efectos nuevos en SVG nativo; exportación mecánica sin pintar píxeles del gato',source:d.id+'/escena.svg',prompt:d.prompt,canvas:{width:W,height:H},frames:d.count,totalMs:sequence.reduce((n,s)=>n+s.ms,0),playback:'once',preview,sequence,original:ref,correction:d.correction,knownLimit:'La pose raster nueva requiere aprobación artística. La pata articula una pieza rígida: no es flexión dibujada. Sin morph entre dibujos ni interpolación generativa. Brillos y signos son ilustraciones; no confirman un pago real.',stages:d.stages,states,generator:'tools/revision-actions.mjs'};
 await writeFile(join(dir,'manifest.json'),JSON.stringify(record,null,2));await writeFile(join(dir,'reglas.json'),JSON.stringify({stages:d.stages,correction:d.correction,generator:record.generator,geometry:{railPivot,railGap:{x:376,y:479,width:96,height:36},shoulder,peek:{hiddenX,shownX,peekY,scale:peekScale,occlusionX:364}},sources:Object.values(layers).map(({uri,...L})=>L)},null,2));records.push(record);
}
await writeFile(join(root,'capas.json'),JSON.stringify({layers:Object.values(layers).map(({uri,...L})=>L)},null,2));
await writeFile(join(root,'comparativas.json'),JSON.stringify({status:'revisión de tres acciones, no reemplaza originales',animations:records.map(({states,...r})=>r)},null,2));
console.log(JSON.stringify({actions:records.length,frames:records.reduce((n,a)=>n+a.frames,0),root}));
