import {readFile,writeFile,mkdir} from 'node:fs/promises';
import {resolve,dirname,join} from 'node:path';
import {fileURLToPath} from 'node:url';
import {spawnSync} from 'node:child_process';
import * as wawoff2 from 'wawoff2';
const lab=resolve(dirname(fileURLToPath(import.meta.url)),'..');
await mkdir(join(lab,'assets/fonts'),{recursive:true});
await mkdir(join(lab,'.qa/fonts'),{recursive:true});
await writeFile(join(lab,'.qa/fonts/recursive-variable.ttf'),Buffer.from(await wawoff2.decompress(await readFile(join(lab,'assets/recursive.woff2')))));
const p=spawnSync('python',[join(lab,'tools/static-fonts.py'),lab],{stdio:'inherit',windowsHide:true});
if(p.status!==0)throw Error('No se pudo instanciar la fuente');
